/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';

/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    chainType: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    transferHash: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    sendAddress: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    receiveAddress: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    assetSymbol: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    assetIcon: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    gas?: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    gasCurrency?: string;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    txType?: number;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    createTime?: number;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    blockHeight?: number;
    /**
     * 
     * @type {Token}
     * @memberof Activity
     */
    payMasterGas?: Token;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    payMasterGasAmount?: string;
}

/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value: object): value is Activity {
    if (!('chainType' in value) || value['chainType'] === undefined) return false;
    if (!('transferHash' in value) || value['transferHash'] === undefined) return false;
    if (!('sendAddress' in value) || value['sendAddress'] === undefined) return false;
    if (!('receiveAddress' in value) || value['receiveAddress'] === undefined) return false;
    if (!('assetSymbol' in value) || value['assetSymbol'] === undefined) return false;
    if (!('assetIcon' in value) || value['assetIcon'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function ActivityFromJSON(json: any): Activity {
    return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activity {
    if (json == null) {
        return json;
    }
    return {
        
        'chainType': json['chainType'],
        'transferHash': json['transferHash'],
        'sendAddress': json['sendAddress'],
        'receiveAddress': json['receiveAddress'],
        'assetSymbol': json['assetSymbol'],
        'assetIcon': json['assetIcon'],
        'amount': json['amount'],
        'gas': json['gas'] == null ? undefined : json['gas'],
        'gasCurrency': json['gasCurrency'] == null ? undefined : json['gasCurrency'],
        'txType': json['txType'] == null ? undefined : json['txType'],
        'status': json['status'] == null ? undefined : json['status'],
        'createTime': json['createTime'] == null ? undefined : json['createTime'],
        'blockHeight': json['blockHeight'] == null ? undefined : json['blockHeight'],
        'payMasterGas': json['payMasterGas'] == null ? undefined : TokenFromJSON(json['payMasterGas']),
        'payMasterGasAmount': json['payMasterGasAmount'] == null ? undefined : json['payMasterGasAmount'],
    };
}

export function ActivityToJSON(json: any): Activity {
    return ActivityToJSONTyped(json, false);
}

export function ActivityToJSONTyped(value?: Activity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chainType': value['chainType'],
        'transferHash': value['transferHash'],
        'sendAddress': value['sendAddress'],
        'receiveAddress': value['receiveAddress'],
        'assetSymbol': value['assetSymbol'],
        'assetIcon': value['assetIcon'],
        'amount': value['amount'],
        'gas': value['gas'],
        'gasCurrency': value['gasCurrency'],
        'txType': value['txType'],
        'status': value['status'],
        'createTime': value['createTime'],
        'blockHeight': value['blockHeight'],
        'payMasterGas': TokenToJSON(value['payMasterGas']),
        'payMasterGasAmount': value['payMasterGasAmount'],
    };
}

