/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnsData } from './EnsData';
import {
    EnsDataFromJSON,
    EnsDataFromJSONTyped,
    EnsDataToJSON,
    EnsDataToJSONTyped,
} from './EnsData';
import type { NetworkFeeData } from './NetworkFeeData';
import {
    NetworkFeeDataFromJSON,
    NetworkFeeDataFromJSONTyped,
    NetworkFeeDataToJSON,
    NetworkFeeDataToJSONTyped,
} from './NetworkFeeData';

/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    chainType: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    transferHash: string;
    /**
     * 
     * @type {EnsData}
     * @memberof Activity
     */
    sendData: EnsData;
    /**
     * 
     * @type {EnsData}
     * @memberof Activity
     */
    receiveData: EnsData;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    assetSymbol: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    assetIcon: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    amount?: string;
    /**
     * 3=received; 4=sent
     * @type {number}
     * @memberof Activity
     */
    txType?: number;
    /**
     * 1=Confirmed 2=Failed 3=Pending
     * @type {number}
     * @memberof Activity
     */
    status?: number;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    createTime?: number;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    blockHeight?: number;
    /**
     * 
     * @type {NetworkFeeData}
     * @memberof Activity
     */
    networkData?: NetworkFeeData;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    chainId: number;
    /**
     * USDT 总价值
     * @type {string}
     * @memberof Activity
     */
    value: string;
}

/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value: object): value is Activity {
    if (!('chainType' in value) || value['chainType'] === undefined) return false;
    if (!('transferHash' in value) || value['transferHash'] === undefined) return false;
    if (!('sendData' in value) || value['sendData'] === undefined) return false;
    if (!('receiveData' in value) || value['receiveData'] === undefined) return false;
    if (!('assetSymbol' in value) || value['assetSymbol'] === undefined) return false;
    if (!('assetIcon' in value) || value['assetIcon'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ActivityFromJSON(json: any): Activity {
    return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activity {
    if (json == null) {
        return json;
    }
    return {
        
        'chainType': json['chainType'],
        'transferHash': json['transferHash'],
        'sendData': EnsDataFromJSON(json['sendData']),
        'receiveData': EnsDataFromJSON(json['receiveData']),
        'assetSymbol': json['assetSymbol'],
        'assetIcon': json['assetIcon'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'txType': json['txType'] == null ? undefined : json['txType'],
        'status': json['status'] == null ? undefined : json['status'],
        'createTime': json['createTime'] == null ? undefined : json['createTime'],
        'blockHeight': json['blockHeight'] == null ? undefined : json['blockHeight'],
        'networkData': json['networkData'] == null ? undefined : NetworkFeeDataFromJSON(json['networkData']),
        'chainId': json['chainId'],
        'value': json['value'],
    };
}

export function ActivityToJSON(json: any): Activity {
    return ActivityToJSONTyped(json, false);
}

export function ActivityToJSONTyped(value?: Activity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chainType': value['chainType'],
        'transferHash': value['transferHash'],
        'sendData': EnsDataToJSON(value['sendData']),
        'receiveData': EnsDataToJSON(value['receiveData']),
        'assetSymbol': value['assetSymbol'],
        'assetIcon': value['assetIcon'],
        'amount': value['amount'],
        'txType': value['txType'],
        'status': value['status'],
        'createTime': value['createTime'],
        'blockHeight': value['blockHeight'],
        'networkData': NetworkFeeDataToJSON(value['networkData']),
        'chainId': value['chainId'],
        'value': value['value'],
    };
}

