/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BotsGet200ResponseError } from './BotsGet200ResponseError';
import {
    BotsGet200ResponseErrorFromJSON,
    BotsGet200ResponseErrorFromJSONTyped,
    BotsGet200ResponseErrorToJSON,
    BotsGet200ResponseErrorToJSONTyped,
} from './BotsGet200ResponseError';

/**
 * 
 * @export
 * @interface BotDetailGet200Response
 */
export interface BotDetailGet200Response {
    /**
     * 
     * @type {string}
     * @memberof BotDetailGet200Response
     */
    result?: string;
    /**
     * 
     * @type {BotsGet200ResponseError}
     * @memberof BotDetailGet200Response
     */
    error: BotsGet200ResponseError;
}

/**
 * Check if a given object implements the BotDetailGet200Response interface.
 */
export function instanceOfBotDetailGet200Response(value: object): value is BotDetailGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function BotDetailGet200ResponseFromJSON(json: any): BotDetailGet200Response {
    return BotDetailGet200ResponseFromJSONTyped(json, false);
}

export function BotDetailGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotDetailGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
        'error': BotsGet200ResponseErrorFromJSON(json['error']),
    };
}

export function BotDetailGet200ResponseToJSON(json: any): BotDetailGet200Response {
    return BotDetailGet200ResponseToJSONTyped(json, false);
}

export function BotDetailGet200ResponseToJSONTyped(value?: BotDetailGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
        'error': BotsGet200ResponseErrorToJSON(value['error']),
    };
}

