/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BotDetailGet200ResponseError
 */
export interface BotDetailGet200ResponseError {
    /**
     * 
     * @type {string}
     * @memberof BotDetailGet200ResponseError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof BotDetailGet200ResponseError
     */
    message: string;
}

/**
 * Check if a given object implements the BotDetailGet200ResponseError interface.
 */
export function instanceOfBotDetailGet200ResponseError(value: object): value is BotDetailGet200ResponseError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function BotDetailGet200ResponseErrorFromJSON(json: any): BotDetailGet200ResponseError {
    return BotDetailGet200ResponseErrorFromJSONTyped(json, false);
}

export function BotDetailGet200ResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotDetailGet200ResponseError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function BotDetailGet200ResponseErrorToJSON(json: any): BotDetailGet200ResponseError {
    return BotDetailGet200ResponseErrorToJSONTyped(json, false);
}

export function BotDetailGet200ResponseErrorToJSONTyped(value?: BotDetailGet200ResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

