/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BotInfoMediasInner } from './BotInfoMediasInner';
import {
    BotInfoMediasInnerFromJSON,
    BotInfoMediasInnerFromJSONTyped,
    BotInfoMediasInnerToJSON,
    BotInfoMediasInnerToJSONTyped,
} from './BotInfoMediasInner';

/**
 * 
 * @export
 * @interface BotInfo
 */
export interface BotInfo {
    /**
     * ID 编号
     * @type {number}
     * @memberof BotInfo
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof BotInfo
     */
    bot_id: number;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    bot_name: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    bot_did: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    owner: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof BotInfo
     */
    create_time: number;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    capabilities: string;
    /**
     * Official website
     * X
     * Ontello
     * Discord
     * Telegram
     * @type {Array<BotInfoMediasInner>}
     * @memberof BotInfo
     */
    medias: Array<BotInfoMediasInner>;
    /**
     * 
     * @type {number}
     * @memberof BotInfo
     */
    users: number;
    /**
     * 
     * @type {number}
     * @memberof BotInfo
     */
    conversations: number;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    llm: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    icon: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    sample_prompts: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    mx_id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BotInfo
     */
    information: Array<string>;
}

/**
 * Check if a given object implements the BotInfo interface.
 */
export function instanceOfBotInfo(value: object): value is BotInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('bot_id' in value) || value['bot_id'] === undefined) return false;
    if (!('bot_name' in value) || value['bot_name'] === undefined) return false;
    if (!('bot_did' in value) || value['bot_did'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('create_time' in value) || value['create_time'] === undefined) return false;
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('medias' in value) || value['medias'] === undefined) return false;
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('conversations' in value) || value['conversations'] === undefined) return false;
    if (!('llm' in value) || value['llm'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('sample_prompts' in value) || value['sample_prompts'] === undefined) return false;
    if (!('mx_id' in value) || value['mx_id'] === undefined) return false;
    if (!('information' in value) || value['information'] === undefined) return false;
    return true;
}

export function BotInfoFromJSON(json: any): BotInfo {
    return BotInfoFromJSONTyped(json, false);
}

export function BotInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bot_id': json['bot_id'],
        'bot_name': json['bot_name'],
        'bot_did': json['bot_did'],
        'owner': json['owner'],
        'description': json['description'],
        'create_time': json['create_time'],
        'capabilities': json['capabilities'],
        'medias': ((json['medias'] as Array<any>).map(BotInfoMediasInnerFromJSON)),
        'users': json['users'],
        'conversations': json['conversations'],
        'llm': json['llm'],
        'icon': json['icon'],
        'sample_prompts': json['sample_prompts'],
        'mx_id': json['mx_id'],
        'information': json['information'],
    };
}

export function BotInfoToJSON(json: any): BotInfo {
    return BotInfoToJSONTyped(json, false);
}

export function BotInfoToJSONTyped(value?: BotInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bot_id': value['bot_id'],
        'bot_name': value['bot_name'],
        'bot_did': value['bot_did'],
        'owner': value['owner'],
        'description': value['description'],
        'create_time': value['create_time'],
        'capabilities': value['capabilities'],
        'medias': ((value['medias'] as Array<any>).map(BotInfoMediasInnerToJSON)),
        'users': value['users'],
        'conversations': value['conversations'],
        'llm': value['llm'],
        'icon': value['icon'],
        'sample_prompts': value['sample_prompts'],
        'mx_id': value['mx_id'],
        'information': value['information'],
    };
}

