/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BotInfo
 */
export interface BotInfo {
    /**
     * ID 编号
     * @type {number}
     * @memberof BotInfo
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof BotInfo
     */
    botId: number;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    botName: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    botDid: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    owner: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    createTime: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    medias: string;
    /**
     * 
     * @type {number}
     * @memberof BotInfo
     */
    users: number;
    /**
     * 
     * @type {number}
     * @memberof BotInfo
     */
    conversations: number;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    llm: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    icon: string;
    /**
     * 
     * @type {string}
     * @memberof BotInfo
     */
    samplePrompts: string;
}

/**
 * Check if a given object implements the BotInfo interface.
 */
export function instanceOfBotInfo(value: object): value is BotInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('botId' in value) || value['botId'] === undefined) return false;
    if (!('botName' in value) || value['botName'] === undefined) return false;
    if (!('botDid' in value) || value['botDid'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('createTime' in value) || value['createTime'] === undefined) return false;
    if (!('medias' in value) || value['medias'] === undefined) return false;
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('conversations' in value) || value['conversations'] === undefined) return false;
    if (!('llm' in value) || value['llm'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('samplePrompts' in value) || value['samplePrompts'] === undefined) return false;
    return true;
}

export function BotInfoFromJSON(json: any): BotInfo {
    return BotInfoFromJSONTyped(json, false);
}

export function BotInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'botId': json['bot_id'],
        'botName': json['bot_name'],
        'botDid': json['bot_did'],
        'owner': json['owner'],
        'description': json['description'],
        'createTime': json['create_time'],
        'medias': json['medias'],
        'users': json['users'],
        'conversations': json['conversations'],
        'llm': json['llm'],
        'icon': json['icon'],
        'samplePrompts': json['sample_prompts'],
    };
}

export function BotInfoToJSON(json: any): BotInfo {
    return BotInfoToJSONTyped(json, false);
}

export function BotInfoToJSONTyped(value?: BotInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bot_id': value['botId'],
        'bot_name': value['botName'],
        'bot_did': value['botDid'],
        'owner': value['owner'],
        'description': value['description'],
        'create_time': value['createTime'],
        'medias': value['medias'],
        'users': value['users'],
        'conversations': value['conversations'],
        'llm': value['llm'],
        'icon': value['icon'],
        'sample_prompts': value['samplePrompts'],
    };
}

