/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokensGet200ResponseError } from './TokensGet200ResponseError';
import {
    TokensGet200ResponseErrorFromJSON,
    TokensGet200ResponseErrorFromJSONTyped,
    TokensGet200ResponseErrorToJSON,
    TokensGet200ResponseErrorToJSONTyped,
} from './TokensGet200ResponseError';
import type { BotsGet200ResponseResult } from './BotsGet200ResponseResult';
import {
    BotsGet200ResponseResultFromJSON,
    BotsGet200ResponseResultFromJSONTyped,
    BotsGet200ResponseResultToJSON,
    BotsGet200ResponseResultToJSONTyped,
} from './BotsGet200ResponseResult';

/**
 * 
 * @export
 * @interface BotsGet200Response
 */
export interface BotsGet200Response {
    /**
     * 
     * @type {TokensGet200ResponseError}
     * @memberof BotsGet200Response
     */
    error: TokensGet200ResponseError;
    /**
     * 
     * @type {BotsGet200ResponseResult}
     * @memberof BotsGet200Response
     */
    result: BotsGet200ResponseResult;
}

/**
 * Check if a given object implements the BotsGet200Response interface.
 */
export function instanceOfBotsGet200Response(value: object): value is BotsGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function BotsGet200ResponseFromJSON(json: any): BotsGet200Response {
    return BotsGet200ResponseFromJSONTyped(json, false);
}

export function BotsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': TokensGet200ResponseErrorFromJSON(json['error']),
        'result': BotsGet200ResponseResultFromJSON(json['result']),
    };
}

export function BotsGet200ResponseToJSON(json: any): BotsGet200Response {
    return BotsGet200ResponseToJSONTyped(json, false);
}

export function BotsGet200ResponseToJSONTyped(value?: BotsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': TokensGet200ResponseErrorToJSON(value['error']),
        'result': BotsGet200ResponseResultToJSON(value['result']),
    };
}

