/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BotInfo } from './BotInfo';
import {
    BotInfoFromJSON,
    BotInfoFromJSONTyped,
    BotInfoToJSON,
    BotInfoToJSONTyped,
} from './BotInfo';

/**
 * 
 * @export
 * @interface BotsGet200ResponseResult
 */
export interface BotsGet200ResponseResult {
    /**
     * 
     * @type {number}
     * @memberof BotsGet200ResponseResult
     */
    total: number;
    /**
     * 
     * @type {Array<BotInfo>}
     * @memberof BotsGet200ResponseResult
     */
    bots: Array<BotInfo>;
}

/**
 * Check if a given object implements the BotsGet200ResponseResult interface.
 */
export function instanceOfBotsGet200ResponseResult(value: object): value is BotsGet200ResponseResult {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('bots' in value) || value['bots'] === undefined) return false;
    return true;
}

export function BotsGet200ResponseResultFromJSON(json: any): BotsGet200ResponseResult {
    return BotsGet200ResponseResultFromJSONTyped(json, false);
}

export function BotsGet200ResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotsGet200ResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'bots': ((json['bots'] as Array<any>).map(BotInfoFromJSON)),
    };
}

export function BotsGet200ResponseResultToJSON(json: any): BotsGet200ResponseResult {
    return BotsGet200ResponseResultToJSONTyped(json, false);
}

export function BotsGet200ResponseResultToJSONTyped(value?: BotsGet200ResponseResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'bots': ((value['bots'] as Array<any>).map(BotInfoToJSON)),
    };
}

