/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Credits } from './Credits';
import {
    CreditsFromJSON,
    CreditsFromJSONTyped,
    CreditsToJSON,
    CreditsToJSONTyped,
} from './Credits';
import type { WalletdataActivityGet200ResponseError } from './WalletdataActivityGet200ResponseError';
import {
    WalletdataActivityGet200ResponseErrorFromJSON,
    WalletdataActivityGet200ResponseErrorFromJSONTyped,
    WalletdataActivityGet200ResponseErrorToJSON,
    WalletdataActivityGet200ResponseErrorToJSONTyped,
} from './WalletdataActivityGet200ResponseError';

/**
 * 
 * @export
 * @interface BusinessCreditsGet200Response
 */
export interface BusinessCreditsGet200Response {
    /**
     * 
     * @type {Credits}
     * @memberof BusinessCreditsGet200Response
     */
    result?: Credits;
    /**
     * 
     * @type {WalletdataActivityGet200ResponseError}
     * @memberof BusinessCreditsGet200Response
     */
    error: WalletdataActivityGet200ResponseError;
}

/**
 * Check if a given object implements the BusinessCreditsGet200Response interface.
 */
export function instanceOfBusinessCreditsGet200Response(value: object): value is BusinessCreditsGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function BusinessCreditsGet200ResponseFromJSON(json: any): BusinessCreditsGet200Response {
    return BusinessCreditsGet200ResponseFromJSONTyped(json, false);
}

export function BusinessCreditsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessCreditsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : CreditsFromJSON(json['result']),
        'error': WalletdataActivityGet200ResponseErrorFromJSON(json['error']),
    };
}

export function BusinessCreditsGet200ResponseToJSON(json: any): BusinessCreditsGet200Response {
    return BusinessCreditsGet200ResponseToJSONTyped(json, false);
}

export function BusinessCreditsGet200ResponseToJSONTyped(value?: BusinessCreditsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': CreditsToJSON(value['result']),
        'error': WalletdataActivityGet200ResponseErrorToJSON(value['error']),
    };
}

