/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletdataActivityGet200ResponseError } from './WalletdataActivityGet200ResponseError';
import {
    WalletdataActivityGet200ResponseErrorFromJSON,
    WalletdataActivityGet200ResponseErrorFromJSONTyped,
    WalletdataActivityGet200ResponseErrorToJSON,
    WalletdataActivityGet200ResponseErrorToJSONTyped,
} from './WalletdataActivityGet200ResponseError';
import type { InviteHistoryList } from './InviteHistoryList';
import {
    InviteHistoryListFromJSON,
    InviteHistoryListFromJSONTyped,
    InviteHistoryListToJSON,
    InviteHistoryListToJSONTyped,
} from './InviteHistoryList';

/**
 * 
 * @export
 * @interface BusinessInviteListGet200Response
 */
export interface BusinessInviteListGet200Response {
    /**
     * 
     * @type {Array<InviteHistoryList>}
     * @memberof BusinessInviteListGet200Response
     */
    result?: Array<InviteHistoryList>;
    /**
     * 
     * @type {WalletdataActivityGet200ResponseError}
     * @memberof BusinessInviteListGet200Response
     */
    error: WalletdataActivityGet200ResponseError;
}

/**
 * Check if a given object implements the BusinessInviteListGet200Response interface.
 */
export function instanceOfBusinessInviteListGet200Response(value: object): value is BusinessInviteListGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function BusinessInviteListGet200ResponseFromJSON(json: any): BusinessInviteListGet200Response {
    return BusinessInviteListGet200ResponseFromJSONTyped(json, false);
}

export function BusinessInviteListGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessInviteListGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(InviteHistoryListFromJSON)),
        'error': WalletdataActivityGet200ResponseErrorFromJSON(json['error']),
    };
}

export function BusinessInviteListGet200ResponseToJSON(json: any): BusinessInviteListGet200Response {
    return BusinessInviteListGet200ResponseToJSONTyped(json, false);
}

export function BusinessInviteListGet200ResponseToJSONTyped(value?: BusinessInviteListGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(InviteHistoryListToJSON)),
        'error': WalletdataActivityGet200ResponseErrorToJSON(value['error']),
    };
}

