/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusinessSaveInvitedCodePostRequest
 */
export interface BusinessSaveInvitedCodePostRequest {
    /**
     * 
     * @type {string}
     * @memberof BusinessSaveInvitedCodePostRequest
     */
    code: string;
}

/**
 * Check if a given object implements the BusinessSaveInvitedCodePostRequest interface.
 */
export function instanceOfBusinessSaveInvitedCodePostRequest(value: object): value is BusinessSaveInvitedCodePostRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function BusinessSaveInvitedCodePostRequestFromJSON(json: any): BusinessSaveInvitedCodePostRequest {
    return BusinessSaveInvitedCodePostRequestFromJSONTyped(json, false);
}

export function BusinessSaveInvitedCodePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessSaveInvitedCodePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function BusinessSaveInvitedCodePostRequestToJSON(json: any): BusinessSaveInvitedCodePostRequest {
    return BusinessSaveInvitedCodePostRequestToJSONTyped(json, false);
}

export function BusinessSaveInvitedCodePostRequestToJSONTyped(value?: BusinessSaveInvitedCodePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

