/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BotInfo } from './BotInfo';
import {
    BotInfoFromJSON,
    BotInfoFromJSONTyped,
    BotInfoToJSON,
    BotInfoToJSONTyped,
} from './BotInfo';

/**
 * 
 * @export
 * @interface BusinessBotsGet200ResponseResult
 */
export interface BusinessBotsGet200ResponseResult {
    /**
     * 
     * @type {number}
     * @memberof BusinessBotsGet200ResponseResult
     */
    total: number;
    /**
     * 
     * @type {Array<BotInfo>}
     * @memberof BusinessBotsGet200ResponseResult
     */
    bots: Array<BotInfo>;
}

/**
 * Check if a given object implements the BusinessBotsGet200ResponseResult interface.
 */
export function instanceOfBusinessBotsGet200ResponseResult(value: object): value is BusinessBotsGet200ResponseResult {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('bots' in value) || value['bots'] === undefined) return false;
    return true;
}

export function BusinessBotsGet200ResponseResultFromJSON(json: any): BusinessBotsGet200ResponseResult {
    return BusinessBotsGet200ResponseResultFromJSONTyped(json, false);
}

export function BusinessBotsGet200ResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessBotsGet200ResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'bots': ((json['bots'] as Array<any>).map(BotInfoFromJSON)),
    };
}

export function BusinessBotsGet200ResponseResultToJSON(json: any): BusinessBotsGet200ResponseResult {
    return BusinessBotsGet200ResponseResultToJSONTyped(json, false);
}

export function BusinessBotsGet200ResponseResultToJSONTyped(value?: BusinessBotsGet200ResponseResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'bots': ((value['bots'] as Array<any>).map(BotInfoToJSON)),
    };
}

