/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletdataActivityGet200ResponseError } from './WalletdataActivityGet200ResponseError';
import {
    WalletdataActivityGet200ResponseErrorFromJSON,
    WalletdataActivityGet200ResponseErrorFromJSONTyped,
    WalletdataActivityGet200ResponseErrorToJSON,
    WalletdataActivityGet200ResponseErrorToJSONTyped,
} from './WalletdataActivityGet200ResponseError';

/**
 * 
 * @export
 * @interface BusinessBotDetailGet200Response
 */
export interface BusinessBotDetailGet200Response {
    /**
     * 
     * @type {string}
     * @memberof BusinessBotDetailGet200Response
     */
    result?: string;
    /**
     * 
     * @type {WalletdataActivityGet200ResponseError}
     * @memberof BusinessBotDetailGet200Response
     */
    error: WalletdataActivityGet200ResponseError;
}

/**
 * Check if a given object implements the BusinessBotDetailGet200Response interface.
 */
export function instanceOfBusinessBotDetailGet200Response(value: object): value is BusinessBotDetailGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function BusinessBotDetailGet200ResponseFromJSON(json: any): BusinessBotDetailGet200Response {
    return BusinessBotDetailGet200ResponseFromJSONTyped(json, false);
}

export function BusinessBotDetailGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessBotDetailGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
        'error': WalletdataActivityGet200ResponseErrorFromJSON(json['error']),
    };
}

export function BusinessBotDetailGet200ResponseToJSON(json: any): BusinessBotDetailGet200Response {
    return BusinessBotDetailGet200ResponseToJSONTyped(json, false);
}

export function BusinessBotDetailGet200ResponseToJSONTyped(value?: BusinessBotDetailGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
        'error': WalletdataActivityGet200ResponseErrorToJSON(value['error']),
    };
}

