/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletdataActivityGet200ResponseError } from './WalletdataActivityGet200ResponseError';
import {
    WalletdataActivityGet200ResponseErrorFromJSON,
    WalletdataActivityGet200ResponseErrorFromJSONTyped,
    WalletdataActivityGet200ResponseErrorToJSON,
    WalletdataActivityGet200ResponseErrorToJSONTyped,
} from './WalletdataActivityGet200ResponseError';
import type { RechargeHistory } from './RechargeHistory';
import {
    RechargeHistoryFromJSON,
    RechargeHistoryFromJSONTyped,
    RechargeHistoryToJSON,
    RechargeHistoryToJSONTyped,
} from './RechargeHistory';

/**
 * 
 * @export
 * @interface BusinessRechargeHistoryGet200Response
 */
export interface BusinessRechargeHistoryGet200Response {
    /**
     * 
     * @type {Array<RechargeHistory>}
     * @memberof BusinessRechargeHistoryGet200Response
     */
    result?: Array<RechargeHistory>;
    /**
     * 
     * @type {WalletdataActivityGet200ResponseError}
     * @memberof BusinessRechargeHistoryGet200Response
     */
    error: WalletdataActivityGet200ResponseError;
}

/**
 * Check if a given object implements the BusinessRechargeHistoryGet200Response interface.
 */
export function instanceOfBusinessRechargeHistoryGet200Response(value: object): value is BusinessRechargeHistoryGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function BusinessRechargeHistoryGet200ResponseFromJSON(json: any): BusinessRechargeHistoryGet200Response {
    return BusinessRechargeHistoryGet200ResponseFromJSONTyped(json, false);
}

export function BusinessRechargeHistoryGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessRechargeHistoryGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(RechargeHistoryFromJSON)),
        'error': WalletdataActivityGet200ResponseErrorFromJSON(json['error']),
    };
}

export function BusinessRechargeHistoryGet200ResponseToJSON(json: any): BusinessRechargeHistoryGet200Response {
    return BusinessRechargeHistoryGet200ResponseToJSONTyped(json, false);
}

export function BusinessRechargeHistoryGet200ResponseToJSONTyped(value?: BusinessRechargeHistoryGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(RechargeHistoryToJSON)),
        'error': WalletdataActivityGet200ResponseErrorToJSON(value['error']),
    };
}

