/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletdataTokensGet200ResponseError } from './WalletdataTokensGet200ResponseError';
import {
    WalletdataTokensGet200ResponseErrorFromJSON,
    WalletdataTokensGet200ResponseErrorFromJSONTyped,
    WalletdataTokensGet200ResponseErrorToJSON,
    WalletdataTokensGet200ResponseErrorToJSONTyped,
} from './WalletdataTokensGet200ResponseError';

/**
 * 
 * @export
 * @interface BusinessUserRoomsGet200Response
 */
export interface BusinessUserRoomsGet200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof BusinessUserRoomsGet200Response
     */
    result?: Array<string>;
    /**
     * 
     * @type {WalletdataTokensGet200ResponseError}
     * @memberof BusinessUserRoomsGet200Response
     */
    error: WalletdataTokensGet200ResponseError;
}

/**
 * Check if a given object implements the BusinessUserRoomsGet200Response interface.
 */
export function instanceOfBusinessUserRoomsGet200Response(value: object): value is BusinessUserRoomsGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function BusinessUserRoomsGet200ResponseFromJSON(json: any): BusinessUserRoomsGet200Response {
    return BusinessUserRoomsGet200ResponseFromJSONTyped(json, false);
}

export function BusinessUserRoomsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessUserRoomsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
        'error': WalletdataTokensGet200ResponseErrorFromJSON(json['error']),
    };
}

export function BusinessUserRoomsGet200ResponseToJSON(json: any): BusinessUserRoomsGet200Response {
    return BusinessUserRoomsGet200ResponseToJSONTyped(json, false);
}

export function BusinessUserRoomsGet200ResponseToJSONTyped(value?: BusinessUserRoomsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
        'error': WalletdataTokensGet200ResponseErrorToJSON(value['error']),
    };
}

