/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessBotsGet200ResponseResult } from './BusinessBotsGet200ResponseResult';
import {
    BusinessBotsGet200ResponseResultFromJSON,
    BusinessBotsGet200ResponseResultFromJSONTyped,
    BusinessBotsGet200ResponseResultToJSON,
    BusinessBotsGet200ResponseResultToJSONTyped,
} from './BusinessBotsGet200ResponseResult';
import type { WalletdataTokensGet200ResponseError } from './WalletdataTokensGet200ResponseError';
import {
    WalletdataTokensGet200ResponseErrorFromJSON,
    WalletdataTokensGet200ResponseErrorFromJSONTyped,
    WalletdataTokensGet200ResponseErrorToJSON,
    WalletdataTokensGet200ResponseErrorToJSONTyped,
} from './WalletdataTokensGet200ResponseError';

/**
 * 
 * @export
 * @interface BusinessBotsGet200Response
 */
export interface BusinessBotsGet200Response {
    /**
     * 
     * @type {WalletdataTokensGet200ResponseError}
     * @memberof BusinessBotsGet200Response
     */
    error: WalletdataTokensGet200ResponseError;
    /**
     * 
     * @type {BusinessBotsGet200ResponseResult}
     * @memberof BusinessBotsGet200Response
     */
    result: BusinessBotsGet200ResponseResult;
}

/**
 * Check if a given object implements the BusinessBotsGet200Response interface.
 */
export function instanceOfBusinessBotsGet200Response(value: object): value is BusinessBotsGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function BusinessBotsGet200ResponseFromJSON(json: any): BusinessBotsGet200Response {
    return BusinessBotsGet200ResponseFromJSONTyped(json, false);
}

export function BusinessBotsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessBotsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': WalletdataTokensGet200ResponseErrorFromJSON(json['error']),
        'result': BusinessBotsGet200ResponseResultFromJSON(json['result']),
    };
}

export function BusinessBotsGet200ResponseToJSON(json: any): BusinessBotsGet200Response {
    return BusinessBotsGet200ResponseToJSONTyped(json, false);
}

export function BusinessBotsGet200ResponseToJSONTyped(value?: BusinessBotsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': WalletdataTokensGet200ResponseErrorToJSON(value['error']),
        'result': BusinessBotsGet200ResponseResultToJSON(value['result']),
    };
}

