/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BusinessRechargeAssetPostRequest
 */
export interface BusinessRechargeAssetPostRequest {
    /**
     * 
     * @type {string}
     * @memberof BusinessRechargeAssetPostRequest
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessRechargeAssetPostRequest
     */
    txHash: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessRechargeAssetPostRequest
     */
    address: string;
    /**
     * 
     * @type {number}
     * @memberof BusinessRechargeAssetPostRequest
     */
    chainID: number;
    /**
     * 
     * @type {string}
     * @memberof BusinessRechargeAssetPostRequest
     */
    tokenAddr: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessRechargeAssetPostRequest
     */
    tokenSymbol: string;
}

/**
 * Check if a given object implements the BusinessRechargeAssetPostRequest interface.
 */
export function instanceOfBusinessRechargeAssetPostRequest(value: object): value is BusinessRechargeAssetPostRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('chainID' in value) || value['chainID'] === undefined) return false;
    if (!('tokenAddr' in value) || value['tokenAddr'] === undefined) return false;
    if (!('tokenSymbol' in value) || value['tokenSymbol'] === undefined) return false;
    return true;
}

export function BusinessRechargeAssetPostRequestFromJSON(json: any): BusinessRechargeAssetPostRequest {
    return BusinessRechargeAssetPostRequestFromJSONTyped(json, false);
}

export function BusinessRechargeAssetPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessRechargeAssetPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'txHash': json['txHash'],
        'address': json['address'],
        'chainID': json['chainID'],
        'tokenAddr': json['tokenAddr'],
        'tokenSymbol': json['tokenSymbol'],
    };
}

export function BusinessRechargeAssetPostRequestToJSON(json: any): BusinessRechargeAssetPostRequest {
    return BusinessRechargeAssetPostRequestToJSONTyped(json, false);
}

export function BusinessRechargeAssetPostRequestToJSONTyped(value?: BusinessRechargeAssetPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'txHash': value['txHash'],
        'address': value['address'],
        'chainID': value['chainID'],
        'tokenAddr': value['tokenAddr'],
        'tokenSymbol': value['tokenSymbol'],
    };
}

