/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BotDetailGet200ResponseError } from './BotDetailGet200ResponseError';
import {
    BotDetailGet200ResponseErrorFromJSON,
    BotDetailGet200ResponseErrorFromJSONTyped,
    BotDetailGet200ResponseErrorToJSON,
    BotDetailGet200ResponseErrorToJSONTyped,
} from './BotDetailGet200ResponseError';
import type { ChainConfig } from './ChainConfig';
import {
    ChainConfigFromJSON,
    ChainConfigFromJSONTyped,
    ChainConfigToJSON,
    ChainConfigToJSONTyped,
} from './ChainConfig';

/**
 * 
 * @export
 * @interface ChainConfigGet200Response
 */
export interface ChainConfigGet200Response {
    /**
     * 
     * @type {BotDetailGet200ResponseError}
     * @memberof ChainConfigGet200Response
     */
    error: BotDetailGet200ResponseError;
    /**
     * 
     * @type {Array<ChainConfig>}
     * @memberof ChainConfigGet200Response
     */
    result: Array<ChainConfig>;
}

/**
 * Check if a given object implements the ChainConfigGet200Response interface.
 */
export function instanceOfChainConfigGet200Response(value: object): value is ChainConfigGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function ChainConfigGet200ResponseFromJSON(json: any): ChainConfigGet200Response {
    return ChainConfigGet200ResponseFromJSONTyped(json, false);
}

export function ChainConfigGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainConfigGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': BotDetailGet200ResponseErrorFromJSON(json['error']),
        'result': ((json['result'] as Array<any>).map(ChainConfigFromJSON)),
    };
}

export function ChainConfigGet200ResponseToJSON(json: any): ChainConfigGet200Response {
    return ChainConfigGet200ResponseToJSONTyped(json, false);
}

export function ChainConfigGet200ResponseToJSONTyped(value?: ChainConfigGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': BotDetailGet200ResponseErrorToJSON(value['error']),
        'result': ((value['result'] as Array<any>).map(ChainConfigToJSON)),
    };
}

