/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';

/**
 * 
 * @export
 * @interface ChainConfig
 */
export interface ChainConfig {
    /**
     * 
     * @type {number}
     * @memberof ChainConfig
     */
    chainId: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChainConfig
     */
    blockExplorerUrls: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ChainConfig
     */
    chainName: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChainConfig
     */
    iconUrls: Array<string>;
    /**
     * 
     * @type {Token}
     * @memberof ChainConfig
     */
    nativeCurrency: Token;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChainConfig
     */
    rpcUrls: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ChainConfig
     */
    entrypointAddr: string;
    /**
     * 
     * @type {string}
     * @memberof ChainConfig
     */
    accountFactoryAddr: string;
    /**
     * 
     * @type {string}
     * @memberof ChainConfig
     */
    paymasterAddr: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChainConfig
     */
    isMain: boolean;
    /**
     * 
     * @type {string}
     * @memberof ChainConfig
     */
    bundlerUrl: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChainConfig
     */
    supportPassKeySign: boolean;
    /**
     * 
     * @type {string}
     * @memberof ChainConfig
     */
    chainNameView: string;
}

/**
 * Check if a given object implements the ChainConfig interface.
 */
export function instanceOfChainConfig(value: object): value is ChainConfig {
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('blockExplorerUrls' in value) || value['blockExplorerUrls'] === undefined) return false;
    if (!('chainName' in value) || value['chainName'] === undefined) return false;
    if (!('iconUrls' in value) || value['iconUrls'] === undefined) return false;
    if (!('nativeCurrency' in value) || value['nativeCurrency'] === undefined) return false;
    if (!('rpcUrls' in value) || value['rpcUrls'] === undefined) return false;
    if (!('entrypointAddr' in value) || value['entrypointAddr'] === undefined) return false;
    if (!('accountFactoryAddr' in value) || value['accountFactoryAddr'] === undefined) return false;
    if (!('paymasterAddr' in value) || value['paymasterAddr'] === undefined) return false;
    if (!('isMain' in value) || value['isMain'] === undefined) return false;
    if (!('bundlerUrl' in value) || value['bundlerUrl'] === undefined) return false;
    if (!('supportPassKeySign' in value) || value['supportPassKeySign'] === undefined) return false;
    if (!('chainNameView' in value) || value['chainNameView'] === undefined) return false;
    return true;
}

export function ChainConfigFromJSON(json: any): ChainConfig {
    return ChainConfigFromJSONTyped(json, false);
}

export function ChainConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'chainId': json['chainId'],
        'blockExplorerUrls': json['blockExplorerUrls'],
        'chainName': json['chainName'],
        'iconUrls': json['iconUrls'],
        'nativeCurrency': TokenFromJSON(json['nativeCurrency']),
        'rpcUrls': json['rpcUrls'],
        'entrypointAddr': json['entrypointAddr'],
        'accountFactoryAddr': json['accountFactoryAddr'],
        'paymasterAddr': json['paymasterAddr'],
        'isMain': json['isMain'],
        'bundlerUrl': json['bundlerUrl'],
        'supportPassKeySign': json['supportPassKeySign'],
        'chainNameView': json['chainNameView'],
    };
}

export function ChainConfigToJSON(json: any): ChainConfig {
    return ChainConfigToJSONTyped(json, false);
}

export function ChainConfigToJSONTyped(value?: ChainConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chainId': value['chainId'],
        'blockExplorerUrls': value['blockExplorerUrls'],
        'chainName': value['chainName'],
        'iconUrls': value['iconUrls'],
        'nativeCurrency': TokenToJSON(value['nativeCurrency']),
        'rpcUrls': value['rpcUrls'],
        'entrypointAddr': value['entrypointAddr'],
        'accountFactoryAddr': value['accountFactoryAddr'],
        'paymasterAddr': value['paymasterAddr'],
        'isMain': value['isMain'],
        'bundlerUrl': value['bundlerUrl'],
        'supportPassKeySign': value['supportPassKeySign'],
        'chainNameView': value['chainNameView'],
    };
}

