/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Credits
 */
export interface Credits {
    /**
     * 
     * @type {string}
     * @memberof Credits
     */
    freeCredits: string;
    /**
     * 
     * @type {string}
     * @memberof Credits
     */
    paidCredits: string;
    /**
     * 
     * @type {string}
     * @memberof Credits
     */
    inviteCredits: string;
    /**
     * 
     * @type {string}
     * @memberof Credits
     */
    totalCredits: string;
}

/**
 * Check if a given object implements the Credits interface.
 */
export function instanceOfCredits(value: object): value is Credits {
    if (!('freeCredits' in value) || value['freeCredits'] === undefined) return false;
    if (!('paidCredits' in value) || value['paidCredits'] === undefined) return false;
    if (!('inviteCredits' in value) || value['inviteCredits'] === undefined) return false;
    if (!('totalCredits' in value) || value['totalCredits'] === undefined) return false;
    return true;
}

export function CreditsFromJSON(json: any): Credits {
    return CreditsFromJSONTyped(json, false);
}

export function CreditsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Credits {
    if (json == null) {
        return json;
    }
    return {
        
        'freeCredits': json['freeCredits'],
        'paidCredits': json['paidCredits'],
        'inviteCredits': json['inviteCredits'],
        'totalCredits': json['totalCredits'],
    };
}

export function CreditsToJSON(json: any): Credits {
    return CreditsToJSONTyped(json, false);
}

export function CreditsToJSONTyped(value?: Credits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'freeCredits': value['freeCredits'],
        'paidCredits': value['paidCredits'],
        'inviteCredits': value['inviteCredits'],
        'totalCredits': value['totalCredits'],
    };
}

