/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnsData
 */
export interface EnsData {
    /**
     * 
     * @type {string}
     * @memberof EnsData
     */
    addr: string;
    /**
     * 
     * @type {string}
     * @memberof EnsData
     */
    domain: string;
    /**
     * 
     * @type {string}
     * @memberof EnsData
     */
    chainIcon: string;
}

/**
 * Check if a given object implements the EnsData interface.
 */
export function instanceOfEnsData(value: object): value is EnsData {
    if (!('addr' in value) || value['addr'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('chainIcon' in value) || value['chainIcon'] === undefined) return false;
    return true;
}

export function EnsDataFromJSON(json: any): EnsData {
    return EnsDataFromJSONTyped(json, false);
}

export function EnsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnsData {
    if (json == null) {
        return json;
    }
    return {
        
        'addr': json['addr'],
        'domain': json['domain'],
        'chainIcon': json['chainIcon'],
    };
}

export function EnsDataToJSON(json: any): EnsData {
    return EnsDataToJSONTyped(json, false);
}

export function EnsDataToJSONTyped(value?: EnsData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addr': value['addr'],
        'domain': value['domain'],
        'chainIcon': value['chainIcon'],
    };
}

