/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokensGet200ResponseError } from './TokensGet200ResponseError';
import {
    TokensGet200ResponseErrorFromJSON,
    TokensGet200ResponseErrorFromJSONTyped,
    TokensGet200ResponseErrorToJSON,
    TokensGet200ResponseErrorToJSONTyped,
} from './TokensGet200ResponseError';
import type { EnsData } from './EnsData';
import {
    EnsDataFromJSON,
    EnsDataFromJSONTyped,
    EnsDataToJSON,
    EnsDataToJSONTyped,
} from './EnsData';

/**
 * 
 * @export
 * @interface EnsGet200Response
 */
export interface EnsGet200Response {
    /**
     * 
     * @type {TokensGet200ResponseError}
     * @memberof EnsGet200Response
     */
    error: TokensGet200ResponseError;
    /**
     * 
     * @type {Array<EnsData>}
     * @memberof EnsGet200Response
     */
    result: Array<EnsData>;
}

/**
 * Check if a given object implements the EnsGet200Response interface.
 */
export function instanceOfEnsGet200Response(value: object): value is EnsGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function EnsGet200ResponseFromJSON(json: any): EnsGet200Response {
    return EnsGet200ResponseFromJSONTyped(json, false);
}

export function EnsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': TokensGet200ResponseErrorFromJSON(json['error']),
        'result': ((json['result'] as Array<any>).map(EnsDataFromJSON)),
    };
}

export function EnsGet200ResponseToJSON(json: any): EnsGet200Response {
    return EnsGet200ResponseToJSONTyped(json, false);
}

export function EnsGet200ResponseToJSONTyped(value?: EnsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': TokensGet200ResponseErrorToJSON(value['error']),
        'result': ((value['result'] as Array<any>).map(EnsDataToJSON)),
    };
}

