/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeRate
 */
export interface ExchangeRate {
    /**
     * 
     * @type {string}
     * @memberof ExchangeRate
     */
    fromTokenPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeRate
     */
    toTokenPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangeRate
     */
    exchangeRate?: string;
}

/**
 * Check if a given object implements the ExchangeRate interface.
 */
export function instanceOfExchangeRate(value: object): value is ExchangeRate {
    return true;
}

export function ExchangeRateFromJSON(json: any): ExchangeRate {
    return ExchangeRateFromJSONTyped(json, false);
}

export function ExchangeRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeRate {
    if (json == null) {
        return json;
    }
    return {
        
        'fromTokenPrice': json['fromTokenPrice'] == null ? undefined : json['fromTokenPrice'],
        'toTokenPrice': json['toTokenPrice'] == null ? undefined : json['toTokenPrice'],
        'exchangeRate': json['exchangeRate'] == null ? undefined : json['exchangeRate'],
    };
}

export function ExchangeRateToJSON(json: any): ExchangeRate {
    return ExchangeRateToJSONTyped(json, false);
}

export function ExchangeRateToJSONTyped(value?: ExchangeRate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromTokenPrice': value['fromTokenPrice'],
        'toTokenPrice': value['toTokenPrice'],
        'exchangeRate': value['exchangeRate'],
    };
}

