/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';

/**
 * 
 * @export
 * @interface FeeSessionResp
 */
export interface FeeSessionResp {
    /**
     * 
     * @type {Token}
     * @memberof FeeSessionResp
     */
    fee: Token;
    /**
     * 
     * @type {string}
     * @memberof FeeSessionResp
     */
    session: string;
    /**
     * 0：否，1：是
     * @type {boolean}
     * @memberof FeeSessionResp
     */
    isPaymaster: boolean;
}

/**
 * Check if a given object implements the FeeSessionResp interface.
 */
export function instanceOfFeeSessionResp(value: object): value is FeeSessionResp {
    if (!('fee' in value) || value['fee'] === undefined) return false;
    if (!('session' in value) || value['session'] === undefined) return false;
    if (!('isPaymaster' in value) || value['isPaymaster'] === undefined) return false;
    return true;
}

export function FeeSessionRespFromJSON(json: any): FeeSessionResp {
    return FeeSessionRespFromJSONTyped(json, false);
}

export function FeeSessionRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeeSessionResp {
    if (json == null) {
        return json;
    }
    return {
        
        'fee': TokenFromJSON(json['fee']),
        'session': json['session'],
        'isPaymaster': json['isPaymaster'],
    };
}

export function FeeSessionRespToJSON(json: any): FeeSessionResp {
    return FeeSessionRespToJSONTyped(json, false);
}

export function FeeSessionRespToJSONTyped(value?: FeeSessionResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fee': TokenToJSON(value['fee']),
        'session': value['session'],
        'isPaymaster': value['isPaymaster'],
    };
}

