/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokensGet200ResponseError } from './TokensGet200ResponseError';
import {
    TokensGet200ResponseErrorFromJSON,
    TokensGet200ResponseErrorFromJSONTyped,
    TokensGet200ResponseErrorToJSON,
    TokensGet200ResponseErrorToJSONTyped,
} from './TokensGet200ResponseError';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';

/**
 * 
 * @export
 * @interface GasTokenGet200Response
 */
export interface GasTokenGet200Response {
    /**
     * 
     * @type {TokensGet200ResponseError}
     * @memberof GasTokenGet200Response
     */
    error: TokensGet200ResponseError;
    /**
     * 
     * @type {Array<Token>}
     * @memberof GasTokenGet200Response
     */
    result: Array<Token>;
}

/**
 * Check if a given object implements the GasTokenGet200Response interface.
 */
export function instanceOfGasTokenGet200Response(value: object): value is GasTokenGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function GasTokenGet200ResponseFromJSON(json: any): GasTokenGet200Response {
    return GasTokenGet200ResponseFromJSONTyped(json, false);
}

export function GasTokenGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GasTokenGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': TokensGet200ResponseErrorFromJSON(json['error']),
        'result': ((json['result'] as Array<any>).map(TokenFromJSON)),
    };
}

export function GasTokenGet200ResponseToJSON(json: any): GasTokenGet200Response {
    return GasTokenGet200ResponseToJSONTyped(json, false);
}

export function GasTokenGet200ResponseToJSONTyped(value?: GasTokenGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': TokensGet200ResponseErrorToJSON(value['error']),
        'result': ((value['result'] as Array<any>).map(TokenToJSON)),
    };
}

