/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteHistoryList
 */
export interface InviteHistoryList {
    /**
     * 
     * @type {string}
     * @memberof InviteHistoryList
     */
    invitee: string;
    /**
     * 
     * @type {number}
     * @memberof InviteHistoryList
     */
    inviteTime: number;
}

/**
 * Check if a given object implements the InviteHistoryList interface.
 */
export function instanceOfInviteHistoryList(value: object): value is InviteHistoryList {
    if (!('invitee' in value) || value['invitee'] === undefined) return false;
    if (!('inviteTime' in value) || value['inviteTime'] === undefined) return false;
    return true;
}

export function InviteHistoryListFromJSON(json: any): InviteHistoryList {
    return InviteHistoryListFromJSONTyped(json, false);
}

export function InviteHistoryListFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteHistoryList {
    if (json == null) {
        return json;
    }
    return {
        
        'invitee': json['invitee'],
        'inviteTime': json['inviteTime'],
    };
}

export function InviteHistoryListToJSON(json: any): InviteHistoryList {
    return InviteHistoryListToJSONTyped(json, false);
}

export function InviteHistoryListToJSONTyped(value?: InviteHistoryList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invitee': value['invitee'],
        'inviteTime': value['inviteTime'],
    };
}

