/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkInfo
 */
export interface LinkInfo {
    /**
     * 
     * @type {string}
     * @memberof LinkInfo
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof LinkInfo
     */
    media: LinkInfoMediaEnum;
}


/**
 * @export
 */
export const LinkInfoMediaEnum = {
    OfficialWebsite: 'Official website',
    X: 'X',
    Ontello: 'Ontello',
    Discord: 'Discord'
} as const;
export type LinkInfoMediaEnum = typeof LinkInfoMediaEnum[keyof typeof LinkInfoMediaEnum];


/**
 * Check if a given object implements the LinkInfo interface.
 */
export function instanceOfLinkInfo(value: object): value is LinkInfo {
    if (!('link' in value) || value['link'] === undefined) return false;
    if (!('media' in value) || value['media'] === undefined) return false;
    return true;
}

export function LinkInfoFromJSON(json: any): LinkInfo {
    return LinkInfoFromJSONTyped(json, false);
}

export function LinkInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'],
        'media': json['media'],
    };
}

export function LinkInfoToJSON(json: any): LinkInfo {
    return LinkInfoToJSONTyped(json, false);
}

export function LinkInfoToJSONTyped(value?: LinkInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'media': value['media'],
    };
}

