/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NetworkFeeData
 */
export interface NetworkFeeData {
    /**
     * 表示network fee token的symbol
     * @type {string}
     * @memberof NetworkFeeData
     */
    networkFeeToken?: string;
    /**
     * 表示手续费的法币价值
     * @type {string}
     * @memberof NetworkFeeData
     */
    networkFeeCurrency?: string;
    /**
     * 表示手续费的数量
     * @type {string}
     * @memberof NetworkFeeData
     */
    networkFee?: string;
}

/**
 * Check if a given object implements the NetworkFeeData interface.
 */
export function instanceOfNetworkFeeData(value: object): value is NetworkFeeData {
    return true;
}

export function NetworkFeeDataFromJSON(json: any): NetworkFeeData {
    return NetworkFeeDataFromJSONTyped(json, false);
}

export function NetworkFeeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkFeeData {
    if (json == null) {
        return json;
    }
    return {
        
        'networkFeeToken': json['networkFeeToken'] == null ? undefined : json['networkFeeToken'],
        'networkFeeCurrency': json['networkFeeCurrency'] == null ? undefined : json['networkFeeCurrency'],
        'networkFee': json['networkFee'] == null ? undefined : json['networkFee'],
    };
}

export function NetworkFeeDataToJSON(json: any): NetworkFeeData {
    return NetworkFeeDataToJSONTyped(json, false);
}

export function NetworkFeeDataToJSONTyped(value?: NetworkFeeData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'networkFeeToken': value['networkFeeToken'],
        'networkFeeCurrency': value['networkFeeCurrency'],
        'networkFee': value['networkFee'],
    };
}

