/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RechargeHistory
 */
export interface RechargeHistory {
    /**
     * 
     * @type {string}
     * @memberof RechargeHistory
     */
    creditsAmount: string;
    /**
     * 
     * @type {string}
     * @memberof RechargeHistory
     */
    tokenAmount: string;
    /**
     * 
     * @type {number}
     * @memberof RechargeHistory
     */
    rechargeTime: number;
}

/**
 * Check if a given object implements the RechargeHistory interface.
 */
export function instanceOfRechargeHistory(value: object): value is RechargeHistory {
    if (!('creditsAmount' in value) || value['creditsAmount'] === undefined) return false;
    if (!('tokenAmount' in value) || value['tokenAmount'] === undefined) return false;
    if (!('rechargeTime' in value) || value['rechargeTime'] === undefined) return false;
    return true;
}

export function RechargeHistoryFromJSON(json: any): RechargeHistory {
    return RechargeHistoryFromJSONTyped(json, false);
}

export function RechargeHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RechargeHistory {
    if (json == null) {
        return json;
    }
    return {
        
        'creditsAmount': json['creditsAmount'],
        'tokenAmount': json['tokenAmount'],
        'rechargeTime': json['rechargeTime'],
    };
}

export function RechargeHistoryToJSON(json: any): RechargeHistory {
    return RechargeHistoryToJSONTyped(json, false);
}

export function RechargeHistoryToJSONTyped(value?: RechargeHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creditsAmount': value['creditsAmount'],
        'tokenAmount': value['tokenAmount'],
        'rechargeTime': value['rechargeTime'],
    };
}

