/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletdataActivityGet200ResponseError } from './WalletdataActivityGet200ResponseError';
import {
    WalletdataActivityGet200ResponseErrorFromJSON,
    WalletdataActivityGet200ResponseErrorFromJSONTyped,
    WalletdataActivityGet200ResponseErrorToJSON,
    WalletdataActivityGet200ResponseErrorToJSONTyped,
} from './WalletdataActivityGet200ResponseError';

/**
 * 
 * @export
 * @interface Response
 */
export interface Response {
    /**
     * 
     * @type {string}
     * @memberof Response
     */
    result: string;
    /**
     * 
     * @type {WalletdataActivityGet200ResponseError}
     * @memberof Response
     */
    error: WalletdataActivityGet200ResponseError;
}

/**
 * Check if a given object implements the Response interface.
 */
export function instanceOfResponse(value: object): value is Response {
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ResponseFromJSON(json: any): Response {
    return ResponseFromJSONTyped(json, false);
}

export function ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'],
        'error': WalletdataActivityGet200ResponseErrorFromJSON(json['error']),
    };
}

export function ResponseToJSON(json: any): Response {
    return ResponseToJSONTyped(json, false);
}

export function ResponseToJSONTyped(value?: Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
        'error': WalletdataActivityGet200ResponseErrorToJSON(value['error']),
    };
}

