/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BotsGet200ResponseError } from './BotsGet200ResponseError';
import {
    BotsGet200ResponseErrorFromJSON,
    BotsGet200ResponseErrorFromJSONTyped,
    BotsGet200ResponseErrorToJSON,
    BotsGet200ResponseErrorToJSONTyped,
} from './BotsGet200ResponseError';

/**
 * 
 * @export
 * @interface Response
 */
export interface Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof Response
     */
    result: Array<string>;
    /**
     * 
     * @type {BotsGet200ResponseError}
     * @memberof Response
     */
    error: BotsGet200ResponseError;
}

/**
 * Check if a given object implements the Response interface.
 */
export function instanceOfResponse(value: object): value is Response {
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ResponseFromJSON(json: any): Response {
    return ResponseFromJSONTyped(json, false);
}

export function ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'],
        'error': BotsGet200ResponseErrorFromJSON(json['error']),
    };
}

export function ResponseToJSON(json: any): Response {
    return ResponseToJSONTyped(json, false);
}

export function ResponseToJSONTyped(value?: Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
        'error': BotsGet200ResponseErrorToJSON(value['error']),
    };
}

