/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    symbol: string;
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    decimals: number;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    icon: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    balance: string;
    /**
     * 总价
     * @type {string}
     * @memberof Token
     */
    currency: string;
    /**
     * 单价
     * @type {string}
     * @memberof Token
     */
    currencyPrice: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    tokenType: string;
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    chainId: number;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    tokenAddr: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    exchangeRate?: string;
}

/**
 * Check if a given object implements the Token interface.
 */
export function instanceOfToken(value: object): value is Token {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('currencyPrice' in value) || value['currencyPrice'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('tokenAddr' in value) || value['tokenAddr'] === undefined) return false;
    return true;
}

export function TokenFromJSON(json: any): Token {
    return TokenFromJSONTyped(json, false);
}

export function TokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'symbol': json['symbol'],
        'decimals': json['decimals'],
        'icon': json['icon'],
        'balance': json['balance'],
        'currency': json['currency'],
        'currencyPrice': json['currencyPrice'],
        'tokenType': json['tokenType'],
        'chainId': json['chainId'],
        'tokenAddr': json['tokenAddr'],
        'exchangeRate': json['exchangeRate'] == null ? undefined : json['exchangeRate'],
    };
}

export function TokenToJSON(json: any): Token {
    return TokenToJSONTyped(json, false);
}

export function TokenToJSONTyped(value?: Token | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'symbol': value['symbol'],
        'decimals': value['decimals'],
        'icon': value['icon'],
        'balance': value['balance'],
        'currency': value['currency'],
        'currencyPrice': value['currencyPrice'],
        'tokenType': value['tokenType'],
        'chainId': value['chainId'],
        'tokenAddr': value['tokenAddr'],
        'exchangeRate': value['exchangeRate'],
    };
}

