/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';
import type { BotDetailGet200ResponseError } from './BotDetailGet200ResponseError';
import {
    BotDetailGet200ResponseErrorFromJSON,
    BotDetailGet200ResponseErrorFromJSONTyped,
    BotDetailGet200ResponseErrorToJSON,
    BotDetailGet200ResponseErrorToJSONTyped,
} from './BotDetailGet200ResponseError';

/**
 * 
 * @export
 * @interface TransferBalanceGet200Response
 */
export interface TransferBalanceGet200Response {
    /**
     * 
     * @type {BotDetailGet200ResponseError}
     * @memberof TransferBalanceGet200Response
     */
    error: BotDetailGet200ResponseError;
    /**
     * 
     * @type {Token}
     * @memberof TransferBalanceGet200Response
     */
    result: Token;
}

/**
 * Check if a given object implements the TransferBalanceGet200Response interface.
 */
export function instanceOfTransferBalanceGet200Response(value: object): value is TransferBalanceGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function TransferBalanceGet200ResponseFromJSON(json: any): TransferBalanceGet200Response {
    return TransferBalanceGet200ResponseFromJSONTyped(json, false);
}

export function TransferBalanceGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferBalanceGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': BotDetailGet200ResponseErrorFromJSON(json['error']),
        'result': TokenFromJSON(json['result']),
    };
}

export function TransferBalanceGet200ResponseToJSON(json: any): TransferBalanceGet200Response {
    return TransferBalanceGet200ResponseToJSONTyped(json, false);
}

export function TransferBalanceGet200ResponseToJSONTyped(value?: TransferBalanceGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': BotDetailGet200ResponseErrorToJSON(value['error']),
        'result': TokenToJSON(value['result']),
    };
}

