/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOperation
 */
export interface UserOperation {
    /**
     * 
     * @type {string}
     * @memberof UserOperation
     */
    sender?: string;
    /**
     * 
     * @type {number}
     * @memberof UserOperation
     */
    nonce?: number;
    /**
     * 
     * @type {string}
     * @memberof UserOperation
     */
    initCode?: string;
    /**
     * 
     * @type {number}
     * @memberof UserOperation
     */
    verificationGasLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserOperation
     */
    preVerificationGas?: number;
    /**
     * 
     * @type {number}
     * @memberof UserOperation
     */
    maxFeePerGas?: number;
    /**
     * 
     * @type {number}
     * @memberof UserOperation
     */
    callGasLimit?: number;
    /**
     * 
     * @type {string}
     * @memberof UserOperation
     */
    callData?: string;
}

/**
 * Check if a given object implements the UserOperation interface.
 */
export function instanceOfUserOperation(value: object): value is UserOperation {
    return true;
}

export function UserOperationFromJSON(json: any): UserOperation {
    return UserOperationFromJSONTyped(json, false);
}

export function UserOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOperation {
    if (json == null) {
        return json;
    }
    return {
        
        'sender': json['sender'] == null ? undefined : json['sender'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'initCode': json['initCode'] == null ? undefined : json['initCode'],
        'verificationGasLimit': json['verificationGasLimit'] == null ? undefined : json['verificationGasLimit'],
        'preVerificationGas': json['preVerificationGas'] == null ? undefined : json['preVerificationGas'],
        'maxFeePerGas': json['maxFeePerGas'] == null ? undefined : json['maxFeePerGas'],
        'callGasLimit': json['callGasLimit'] == null ? undefined : json['callGasLimit'],
        'callData': json['callData'] == null ? undefined : json['callData'],
    };
}

export function UserOperationToJSON(json: any): UserOperation {
    return UserOperationToJSONTyped(json, false);
}

export function UserOperationToJSONTyped(value?: UserOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sender': value['sender'],
        'nonce': value['nonce'],
        'initCode': value['initCode'],
        'verificationGasLimit': value['verificationGasLimit'],
        'preVerificationGas': value['preVerificationGas'],
        'maxFeePerGas': value['maxFeePerGas'],
        'callGasLimit': value['callGasLimit'],
        'callData': value['callData'],
    };
}

