/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokensGet200ResponseError } from './TokensGet200ResponseError';
import {
    TokensGet200ResponseErrorFromJSON,
    TokensGet200ResponseErrorFromJSONTyped,
    TokensGet200ResponseErrorToJSON,
    TokensGet200ResponseErrorToJSONTyped,
} from './TokensGet200ResponseError';

/**
 * 
 * @export
 * @interface UserRoomsGet200Response
 */
export interface UserRoomsGet200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof UserRoomsGet200Response
     */
    result?: Array<string>;
    /**
     * 
     * @type {TokensGet200ResponseError}
     * @memberof UserRoomsGet200Response
     */
    error: TokensGet200ResponseError;
}

/**
 * Check if a given object implements the UserRoomsGet200Response interface.
 */
export function instanceOfUserRoomsGet200Response(value: object): value is UserRoomsGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function UserRoomsGet200ResponseFromJSON(json: any): UserRoomsGet200Response {
    return UserRoomsGet200ResponseFromJSONTyped(json, false);
}

export function UserRoomsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoomsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
        'error': TokensGet200ResponseErrorFromJSON(json['error']),
    };
}

export function UserRoomsGet200ResponseToJSON(json: any): UserRoomsGet200Response {
    return UserRoomsGet200ResponseToJSONTyped(json, false);
}

export function UserRoomsGet200ResponseToJSONTyped(value?: UserRoomsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
        'error': TokensGet200ResponseErrorToJSON(value['error']),
    };
}

