/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletdataActivityGet200ResponseError } from './WalletdataActivityGet200ResponseError';
import {
    WalletdataActivityGet200ResponseErrorFromJSON,
    WalletdataActivityGet200ResponseErrorFromJSONTyped,
    WalletdataActivityGet200ResponseErrorToJSON,
    WalletdataActivityGet200ResponseErrorToJSONTyped,
} from './WalletdataActivityGet200ResponseError';
import type { ChainConfig } from './ChainConfig';
import {
    ChainConfigFromJSON,
    ChainConfigFromJSONTyped,
    ChainConfigToJSON,
    ChainConfigToJSONTyped,
} from './ChainConfig';

/**
 * 
 * @export
 * @interface WalletdataChainConfigGet200Response
 */
export interface WalletdataChainConfigGet200Response {
    /**
     * 
     * @type {WalletdataActivityGet200ResponseError}
     * @memberof WalletdataChainConfigGet200Response
     */
    error: WalletdataActivityGet200ResponseError;
    /**
     * 
     * @type {Array<ChainConfig>}
     * @memberof WalletdataChainConfigGet200Response
     */
    result: Array<ChainConfig>;
}

/**
 * Check if a given object implements the WalletdataChainConfigGet200Response interface.
 */
export function instanceOfWalletdataChainConfigGet200Response(value: object): value is WalletdataChainConfigGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function WalletdataChainConfigGet200ResponseFromJSON(json: any): WalletdataChainConfigGet200Response {
    return WalletdataChainConfigGet200ResponseFromJSONTyped(json, false);
}

export function WalletdataChainConfigGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataChainConfigGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': WalletdataActivityGet200ResponseErrorFromJSON(json['error']),
        'result': ((json['result'] as Array<any>).map(ChainConfigFromJSON)),
    };
}

export function WalletdataChainConfigGet200ResponseToJSON(json: any): WalletdataChainConfigGet200Response {
    return WalletdataChainConfigGet200ResponseToJSONTyped(json, false);
}

export function WalletdataChainConfigGet200ResponseToJSONTyped(value?: WalletdataChainConfigGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': WalletdataActivityGet200ResponseErrorToJSON(value['error']),
        'result': ((value['result'] as Array<any>).map(ChainConfigToJSON)),
    };
}

