/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletdataActivityGet200ResponseError } from './WalletdataActivityGet200ResponseError';
import {
    WalletdataActivityGet200ResponseErrorFromJSON,
    WalletdataActivityGet200ResponseErrorFromJSONTyped,
    WalletdataActivityGet200ResponseErrorToJSON,
    WalletdataActivityGet200ResponseErrorToJSONTyped,
} from './WalletdataActivityGet200ResponseError';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';

/**
 * 
 * @export
 * @interface WalletdataGasTokenGet200Response
 */
export interface WalletdataGasTokenGet200Response {
    /**
     * 
     * @type {WalletdataActivityGet200ResponseError}
     * @memberof WalletdataGasTokenGet200Response
     */
    error: WalletdataActivityGet200ResponseError;
    /**
     * 
     * @type {Array<Token>}
     * @memberof WalletdataGasTokenGet200Response
     */
    result: Array<Token>;
}

/**
 * Check if a given object implements the WalletdataGasTokenGet200Response interface.
 */
export function instanceOfWalletdataGasTokenGet200Response(value: object): value is WalletdataGasTokenGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function WalletdataGasTokenGet200ResponseFromJSON(json: any): WalletdataGasTokenGet200Response {
    return WalletdataGasTokenGet200ResponseFromJSONTyped(json, false);
}

export function WalletdataGasTokenGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataGasTokenGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': WalletdataActivityGet200ResponseErrorFromJSON(json['error']),
        'result': ((json['result'] as Array<any>).map(TokenFromJSON)),
    };
}

export function WalletdataGasTokenGet200ResponseToJSON(json: any): WalletdataGasTokenGet200Response {
    return WalletdataGasTokenGet200ResponseToJSONTyped(json, false);
}

export function WalletdataGasTokenGet200ResponseToJSONTyped(value?: WalletdataGasTokenGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': WalletdataActivityGet200ResponseErrorToJSON(value['error']),
        'result': ((value['result'] as Array<any>).map(TokenToJSON)),
    };
}

