/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnsData } from './EnsData';
import {
    EnsDataFromJSON,
    EnsDataFromJSONTyped,
    EnsDataToJSON,
    EnsDataToJSONTyped,
} from './EnsData';
import type { WalletdataTokensGet200ResponseError } from './WalletdataTokensGet200ResponseError';
import {
    WalletdataTokensGet200ResponseErrorFromJSON,
    WalletdataTokensGet200ResponseErrorFromJSONTyped,
    WalletdataTokensGet200ResponseErrorToJSON,
    WalletdataTokensGet200ResponseErrorToJSONTyped,
} from './WalletdataTokensGet200ResponseError';

/**
 * 
 * @export
 * @interface WalletdataEnsGet200Response
 */
export interface WalletdataEnsGet200Response {
    /**
     * 
     * @type {WalletdataTokensGet200ResponseError}
     * @memberof WalletdataEnsGet200Response
     */
    error: WalletdataTokensGet200ResponseError;
    /**
     * 
     * @type {Array<EnsData>}
     * @memberof WalletdataEnsGet200Response
     */
    result: Array<EnsData>;
}

/**
 * Check if a given object implements the WalletdataEnsGet200Response interface.
 */
export function instanceOfWalletdataEnsGet200Response(value: object): value is WalletdataEnsGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function WalletdataEnsGet200ResponseFromJSON(json: any): WalletdataEnsGet200Response {
    return WalletdataEnsGet200ResponseFromJSONTyped(json, false);
}

export function WalletdataEnsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataEnsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': WalletdataTokensGet200ResponseErrorFromJSON(json['error']),
        'result': ((json['result'] as Array<any>).map(EnsDataFromJSON)),
    };
}

export function WalletdataEnsGet200ResponseToJSON(json: any): WalletdataEnsGet200Response {
    return WalletdataEnsGet200ResponseToJSONTyped(json, false);
}

export function WalletdataEnsGet200ResponseToJSONTyped(value?: WalletdataEnsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': WalletdataTokensGet200ResponseErrorToJSON(value['error']),
        'result': ((value['result'] as Array<any>).map(EnsDataToJSON)),
    };
}

