/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';
import type { WalletdataTokensGet200ResponseError } from './WalletdataTokensGet200ResponseError';
import {
    WalletdataTokensGet200ResponseErrorFromJSON,
    WalletdataTokensGet200ResponseErrorFromJSONTyped,
    WalletdataTokensGet200ResponseErrorToJSON,
    WalletdataTokensGet200ResponseErrorToJSONTyped,
} from './WalletdataTokensGet200ResponseError';

/**
 * 
 * @export
 * @interface WalletdataTransferBalanceGet200Response
 */
export interface WalletdataTransferBalanceGet200Response {
    /**
     * 
     * @type {WalletdataTokensGet200ResponseError}
     * @memberof WalletdataTransferBalanceGet200Response
     */
    error: WalletdataTokensGet200ResponseError;
    /**
     * 
     * @type {Token}
     * @memberof WalletdataTransferBalanceGet200Response
     */
    result: Token;
}

/**
 * Check if a given object implements the WalletdataTransferBalanceGet200Response interface.
 */
export function instanceOfWalletdataTransferBalanceGet200Response(value: object): value is WalletdataTransferBalanceGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function WalletdataTransferBalanceGet200ResponseFromJSON(json: any): WalletdataTransferBalanceGet200Response {
    return WalletdataTransferBalanceGet200ResponseFromJSONTyped(json, false);
}

export function WalletdataTransferBalanceGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataTransferBalanceGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': WalletdataTokensGet200ResponseErrorFromJSON(json['error']),
        'result': TokenFromJSON(json['result']),
    };
}

export function WalletdataTransferBalanceGet200ResponseToJSON(json: any): WalletdataTransferBalanceGet200Response {
    return WalletdataTransferBalanceGet200ResponseToJSONTyped(json, false);
}

export function WalletdataTransferBalanceGet200ResponseToJSONTyped(value?: WalletdataTransferBalanceGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': WalletdataTokensGet200ResponseErrorToJSON(value['error']),
        'result': TokenToJSON(value['result']),
    };
}

