/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletdataActivityGet200ResponseError } from './WalletdataActivityGet200ResponseError';
import {
    WalletdataActivityGet200ResponseErrorFromJSON,
    WalletdataActivityGet200ResponseErrorFromJSONTyped,
    WalletdataActivityGet200ResponseErrorToJSON,
    WalletdataActivityGet200ResponseErrorToJSONTyped,
} from './WalletdataActivityGet200ResponseError';
import type { FeeSessionResp } from './FeeSessionResp';
import {
    FeeSessionRespFromJSON,
    FeeSessionRespFromJSONTyped,
    FeeSessionRespToJSON,
    FeeSessionRespToJSONTyped,
} from './FeeSessionResp';

/**
 * 
 * @export
 * @interface WalletdataChangeOwnerPost200Response
 */
export interface WalletdataChangeOwnerPost200Response {
    /**
     * 
     * @type {WalletdataActivityGet200ResponseError}
     * @memberof WalletdataChangeOwnerPost200Response
     */
    error: WalletdataActivityGet200ResponseError;
    /**
     * 
     * @type {FeeSessionResp}
     * @memberof WalletdataChangeOwnerPost200Response
     */
    result: FeeSessionResp;
}

/**
 * Check if a given object implements the WalletdataChangeOwnerPost200Response interface.
 */
export function instanceOfWalletdataChangeOwnerPost200Response(value: object): value is WalletdataChangeOwnerPost200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function WalletdataChangeOwnerPost200ResponseFromJSON(json: any): WalletdataChangeOwnerPost200Response {
    return WalletdataChangeOwnerPost200ResponseFromJSONTyped(json, false);
}

export function WalletdataChangeOwnerPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataChangeOwnerPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': WalletdataActivityGet200ResponseErrorFromJSON(json['error']),
        'result': FeeSessionRespFromJSON(json['result']),
    };
}

export function WalletdataChangeOwnerPost200ResponseToJSON(json: any): WalletdataChangeOwnerPost200Response {
    return WalletdataChangeOwnerPost200ResponseToJSONTyped(json, false);
}

export function WalletdataChangeOwnerPost200ResponseToJSONTyped(value?: WalletdataChangeOwnerPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': WalletdataActivityGet200ResponseErrorToJSON(value['error']),
        'result': FeeSessionRespToJSON(value['result']),
    };
}

