/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletdataActivityGet200ResponseError } from './WalletdataActivityGet200ResponseError';
import {
    WalletdataActivityGet200ResponseErrorFromJSON,
    WalletdataActivityGet200ResponseErrorFromJSONTyped,
    WalletdataActivityGet200ResponseErrorToJSON,
    WalletdataActivityGet200ResponseErrorToJSONTyped,
} from './WalletdataActivityGet200ResponseError';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
    TokenToJSONTyped,
} from './Token';

/**
 * 
 * @export
 * @interface WalletdataTokensGet200Response
 */
export interface WalletdataTokensGet200Response {
    /**
     * 
     * @type {WalletdataActivityGet200ResponseError}
     * @memberof WalletdataTokensGet200Response
     */
    error: WalletdataActivityGet200ResponseError;
    /**
     * 
     * @type {Array<Token>}
     * @memberof WalletdataTokensGet200Response
     */
    result: Array<Token>;
}

/**
 * Check if a given object implements the WalletdataTokensGet200Response interface.
 */
export function instanceOfWalletdataTokensGet200Response(value: object): value is WalletdataTokensGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function WalletdataTokensGet200ResponseFromJSON(json: any): WalletdataTokensGet200Response {
    return WalletdataTokensGet200ResponseFromJSONTyped(json, false);
}

export function WalletdataTokensGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataTokensGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': WalletdataActivityGet200ResponseErrorFromJSON(json['error']),
        'result': ((json['result'] as Array<any>).map(TokenFromJSON)),
    };
}

export function WalletdataTokensGet200ResponseToJSON(json: any): WalletdataTokensGet200Response {
    return WalletdataTokensGet200ResponseToJSONTyped(json, false);
}

export function WalletdataTokensGet200ResponseToJSONTyped(value?: WalletdataTokensGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': WalletdataActivityGet200ResponseErrorToJSON(value['error']),
        'result': ((value['result'] as Array<any>).map(TokenToJSON)),
    };
}

