/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletdataActivityGet200ResponseError } from './WalletdataActivityGet200ResponseError';
import {
    WalletdataActivityGet200ResponseErrorFromJSON,
    WalletdataActivityGet200ResponseErrorFromJSONTyped,
    WalletdataActivityGet200ResponseErrorToJSON,
    WalletdataActivityGet200ResponseErrorToJSONTyped,
} from './WalletdataActivityGet200ResponseError';

/**
 * 
 * @export
 * @interface WalletdataConfirmPaymentPost200Response
 */
export interface WalletdataConfirmPaymentPost200Response {
    /**
     * 
     * @type {WalletdataActivityGet200ResponseError}
     * @memberof WalletdataConfirmPaymentPost200Response
     */
    error: WalletdataActivityGet200ResponseError;
    /**
     * 
     * @type {string}
     * @memberof WalletdataConfirmPaymentPost200Response
     */
    result: string;
}

/**
 * Check if a given object implements the WalletdataConfirmPaymentPost200Response interface.
 */
export function instanceOfWalletdataConfirmPaymentPost200Response(value: object): value is WalletdataConfirmPaymentPost200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function WalletdataConfirmPaymentPost200ResponseFromJSON(json: any): WalletdataConfirmPaymentPost200Response {
    return WalletdataConfirmPaymentPost200ResponseFromJSONTyped(json, false);
}

export function WalletdataConfirmPaymentPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataConfirmPaymentPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': WalletdataActivityGet200ResponseErrorFromJSON(json['error']),
        'result': json['result'],
    };
}

export function WalletdataConfirmPaymentPost200ResponseToJSON(json: any): WalletdataConfirmPaymentPost200Response {
    return WalletdataConfirmPaymentPost200ResponseToJSONTyped(json, false);
}

export function WalletdataConfirmPaymentPost200ResponseToJSONTyped(value?: WalletdataConfirmPaymentPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': WalletdataActivityGet200ResponseErrorToJSON(value['error']),
        'result': value['result'],
    };
}

