/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletdataConfirmPaymentPostRequest
 */
export interface WalletdataConfirmPaymentPostRequest {
    /**
     * 
     * @type {string}
     * @memberof WalletdataConfirmPaymentPostRequest
     */
    session: string;
}

/**
 * Check if a given object implements the WalletdataConfirmPaymentPostRequest interface.
 */
export function instanceOfWalletdataConfirmPaymentPostRequest(value: object): value is WalletdataConfirmPaymentPostRequest {
    if (!('session' in value) || value['session'] === undefined) return false;
    return true;
}

export function WalletdataConfirmPaymentPostRequestFromJSON(json: any): WalletdataConfirmPaymentPostRequest {
    return WalletdataConfirmPaymentPostRequestFromJSONTyped(json, false);
}

export function WalletdataConfirmPaymentPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataConfirmPaymentPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'session': json['session'],
    };
}

export function WalletdataConfirmPaymentPostRequestToJSON(json: any): WalletdataConfirmPaymentPostRequest {
    return WalletdataConfirmPaymentPostRequestToJSONTyped(json, false);
}

export function WalletdataConfirmPaymentPostRequestToJSONTyped(value?: WalletdataConfirmPaymentPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'session': value['session'],
    };
}

