/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletdataActivityGet200ResponseError } from './WalletdataActivityGet200ResponseError';
import {
    WalletdataActivityGet200ResponseErrorFromJSON,
    WalletdataActivityGet200ResponseErrorFromJSONTyped,
    WalletdataActivityGet200ResponseErrorToJSON,
    WalletdataActivityGet200ResponseErrorToJSONTyped,
} from './WalletdataActivityGet200ResponseError';
import type { WalletdataActivityGet200ResponseResult } from './WalletdataActivityGet200ResponseResult';
import {
    WalletdataActivityGet200ResponseResultFromJSON,
    WalletdataActivityGet200ResponseResultFromJSONTyped,
    WalletdataActivityGet200ResponseResultToJSON,
    WalletdataActivityGet200ResponseResultToJSONTyped,
} from './WalletdataActivityGet200ResponseResult';

/**
 * 
 * @export
 * @interface WalletdataActivityGet200Response
 */
export interface WalletdataActivityGet200Response {
    /**
     * 
     * @type {WalletdataActivityGet200ResponseError}
     * @memberof WalletdataActivityGet200Response
     */
    error: WalletdataActivityGet200ResponseError;
    /**
     * 
     * @type {WalletdataActivityGet200ResponseResult}
     * @memberof WalletdataActivityGet200Response
     */
    result: WalletdataActivityGet200ResponseResult;
}

/**
 * Check if a given object implements the WalletdataActivityGet200Response interface.
 */
export function instanceOfWalletdataActivityGet200Response(value: object): value is WalletdataActivityGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function WalletdataActivityGet200ResponseFromJSON(json: any): WalletdataActivityGet200Response {
    return WalletdataActivityGet200ResponseFromJSONTyped(json, false);
}

export function WalletdataActivityGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataActivityGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': WalletdataActivityGet200ResponseErrorFromJSON(json['error']),
        'result': WalletdataActivityGet200ResponseResultFromJSON(json['result']),
    };
}

export function WalletdataActivityGet200ResponseToJSON(json: any): WalletdataActivityGet200Response {
    return WalletdataActivityGet200ResponseToJSONTyped(json, false);
}

export function WalletdataActivityGet200ResponseToJSONTyped(value?: WalletdataActivityGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': WalletdataActivityGet200ResponseErrorToJSON(value['error']),
        'result': WalletdataActivityGet200ResponseResultToJSON(value['result']),
    };
}

