/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletdataRelayChainPostRequest
 */
export interface WalletdataRelayChainPostRequest {
    /**
     * 
     * @type {string}
     * @memberof WalletdataRelayChainPostRequest
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof WalletdataRelayChainPostRequest
     */
    token: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof WalletdataRelayChainPostRequest
     */
    chainId: Array<number>;
}

/**
 * Check if a given object implements the WalletdataRelayChainPostRequest interface.
 */
export function instanceOfWalletdataRelayChainPostRequest(value: object): value is WalletdataRelayChainPostRequest {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    return true;
}

export function WalletdataRelayChainPostRequestFromJSON(json: any): WalletdataRelayChainPostRequest {
    return WalletdataRelayChainPostRequestFromJSONTyped(json, false);
}

export function WalletdataRelayChainPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataRelayChainPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'token': json['token'],
        'chainId': json['chainId'],
    };
}

export function WalletdataRelayChainPostRequestToJSON(json: any): WalletdataRelayChainPostRequest {
    return WalletdataRelayChainPostRequestToJSONTyped(json, false);
}

export function WalletdataRelayChainPostRequestToJSONTyped(value?: WalletdataRelayChainPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'token': value['token'],
        'chainId': value['chainId'],
    };
}

