/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeRate } from './ExchangeRate';
import {
    ExchangeRateFromJSON,
    ExchangeRateFromJSONTyped,
    ExchangeRateToJSON,
    ExchangeRateToJSONTyped,
} from './ExchangeRate';
import type { WalletdataActivityGet200ResponseError } from './WalletdataActivityGet200ResponseError';
import {
    WalletdataActivityGet200ResponseErrorFromJSON,
    WalletdataActivityGet200ResponseErrorFromJSONTyped,
    WalletdataActivityGet200ResponseErrorToJSON,
    WalletdataActivityGet200ResponseErrorToJSONTyped,
} from './WalletdataActivityGet200ResponseError';

/**
 * 
 * @export
 * @interface WalletdataExchangeRateGet200Response
 */
export interface WalletdataExchangeRateGet200Response {
    /**
     * 
     * @type {WalletdataActivityGet200ResponseError}
     * @memberof WalletdataExchangeRateGet200Response
     */
    error: WalletdataActivityGet200ResponseError;
    /**
     * 
     * @type {ExchangeRate}
     * @memberof WalletdataExchangeRateGet200Response
     */
    result: ExchangeRate;
}

/**
 * Check if a given object implements the WalletdataExchangeRateGet200Response interface.
 */
export function instanceOfWalletdataExchangeRateGet200Response(value: object): value is WalletdataExchangeRateGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function WalletdataExchangeRateGet200ResponseFromJSON(json: any): WalletdataExchangeRateGet200Response {
    return WalletdataExchangeRateGet200ResponseFromJSONTyped(json, false);
}

export function WalletdataExchangeRateGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataExchangeRateGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': WalletdataActivityGet200ResponseErrorFromJSON(json['error']),
        'result': ExchangeRateFromJSON(json['result']),
    };
}

export function WalletdataExchangeRateGet200ResponseToJSON(json: any): WalletdataExchangeRateGet200Response {
    return WalletdataExchangeRateGet200ResponseToJSONTyped(json, false);
}

export function WalletdataExchangeRateGet200ResponseToJSONTyped(value?: WalletdataExchangeRateGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': WalletdataActivityGet200ResponseErrorToJSON(value['error']),
        'result': ExchangeRateToJSON(value['result']),
    };
}

