/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Activity } from './Activity';
import {
    ActivityFromJSON,
    ActivityFromJSONTyped,
    ActivityToJSON,
    ActivityToJSONTyped,
} from './Activity';

/**
 * 
 * @export
 * @interface WalletdataActivityGet200ResponseResult
 */
export interface WalletdataActivityGet200ResponseResult {
    /**
     * 
     * @type {number}
     * @memberof WalletdataActivityGet200ResponseResult
     */
    total: number;
    /**
     * 
     * @type {Array<Activity>}
     * @memberof WalletdataActivityGet200ResponseResult
     */
    records: Array<Activity>;
}

/**
 * Check if a given object implements the WalletdataActivityGet200ResponseResult interface.
 */
export function instanceOfWalletdataActivityGet200ResponseResult(value: object): value is WalletdataActivityGet200ResponseResult {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function WalletdataActivityGet200ResponseResultFromJSON(json: any): WalletdataActivityGet200ResponseResult {
    return WalletdataActivityGet200ResponseResultFromJSONTyped(json, false);
}

export function WalletdataActivityGet200ResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataActivityGet200ResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(ActivityFromJSON)),
    };
}

export function WalletdataActivityGet200ResponseResultToJSON(json: any): WalletdataActivityGet200ResponseResult {
    return WalletdataActivityGet200ResponseResultToJSONTyped(json, false);
}

export function WalletdataActivityGet200ResponseResultToJSONTyped(value?: WalletdataActivityGet200ResponseResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(ActivityToJSON)),
    };
}

