/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserOperation } from './UserOperation';
import {
    UserOperationFromJSON,
    UserOperationFromJSONTyped,
    UserOperationToJSON,
    UserOperationToJSONTyped,
} from './UserOperation';

/**
 * 
 * @export
 * @interface WalletdataChangeOwnerPostRequest
 */
export interface WalletdataChangeOwnerPostRequest {
    /**
     * 
     * @type {UserOperation}
     * @memberof WalletdataChangeOwnerPostRequest
     */
    userOperation: UserOperation;
    /**
     * 
     * @type {string}
     * @memberof WalletdataChangeOwnerPostRequest
     */
    token: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof WalletdataChangeOwnerPostRequest
     */
    chainId: Array<number>;
}

/**
 * Check if a given object implements the WalletdataChangeOwnerPostRequest interface.
 */
export function instanceOfWalletdataChangeOwnerPostRequest(value: object): value is WalletdataChangeOwnerPostRequest {
    if (!('userOperation' in value) || value['userOperation'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    return true;
}

export function WalletdataChangeOwnerPostRequestFromJSON(json: any): WalletdataChangeOwnerPostRequest {
    return WalletdataChangeOwnerPostRequestFromJSONTyped(json, false);
}

export function WalletdataChangeOwnerPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletdataChangeOwnerPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userOperation': UserOperationFromJSON(json['userOperation']),
        'token': json['token'],
        'chainId': json['chainId'],
    };
}

export function WalletdataChangeOwnerPostRequestToJSON(json: any): WalletdataChangeOwnerPostRequest {
    return WalletdataChangeOwnerPostRequestToJSONTyped(json, false);
}

export function WalletdataChangeOwnerPostRequestToJSONTyped(value?: WalletdataChangeOwnerPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userOperation': UserOperationToJSON(value['userOperation']),
        'token': value['token'],
        'chainId': value['chainId'],
    };
}

