/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BusinessBotDetailGet200Response,
  BusinessBotsGet200Response,
  BusinessUserRoomsGet200Response,
} from '../models/index';
import {
    BusinessBotDetailGet200ResponseFromJSON,
    BusinessBotDetailGet200ResponseToJSON,
    BusinessBotsGet200ResponseFromJSON,
    BusinessBotsGet200ResponseToJSON,
    BusinessUserRoomsGet200ResponseFromJSON,
    BusinessUserRoomsGet200ResponseToJSON,
} from '../models/index';

export interface BusinessBotDetailGetRequest {
    bot_id?: number;
    bot_did?: string;
}

export interface BusinessBotsGetRequest {
    page_no?: number;
    page_size?: number;
    keyword?: string;
    body?: object;
}

export interface BusinessUserRoomsGetRequest {
    authorization?: string;
}

/**
 * 
 */
export class ImBotApi extends runtime.BaseAPI {

    /**
     * 输入参数为bot_id或bot_did
     * get bot detail info
     */
    async businessBotDetailGetRaw(requestParameters: BusinessBotDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessBotDetailGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['bot_id'] != null) {
            queryParameters['bot_id'] = requestParameters['bot_id'];
        }

        if (requestParameters['bot_did'] != null) {
            queryParameters['bot_did'] = requestParameters['bot_did'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/business/bot/detail`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessBotDetailGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 输入参数为bot_id或bot_did
     * get bot detail info
     */
    async businessBotDetailGet(requestParameters: BusinessBotDetailGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessBotDetailGet200Response> {
        const response = await this.businessBotDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * get all bots
     */
    async businessBotsGetRaw(requestParameters: BusinessBotsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessBotsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page_no'] != null) {
            queryParameters['page_no'] = requestParameters['page_no'];
        }

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/business/bots`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessBotsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * get all bots
     */
    async businessBotsGet(requestParameters: BusinessBotsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessBotsGet200Response> {
        const response = await this.businessBotsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * user_id  like. @tasktalk:matrix.org
     * get user rooms
     */
    async businessUserRoomsGetRaw(requestParameters: BusinessUserRoomsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessUserRoomsGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/business/user/rooms`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessUserRoomsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * user_id  like. @tasktalk:matrix.org
     * get user rooms
     */
    async businessUserRoomsGet(requestParameters: BusinessUserRoomsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessUserRoomsGet200Response> {
        const response = await this.businessUserRoomsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
