/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BotDetailGet200Response,
  BotsGet200Response,
  UserRoomsGet200Response,
} from '../models/index';
import {
    BotDetailGet200ResponseFromJSON,
    BotDetailGet200ResponseToJSON,
    BotsGet200ResponseFromJSON,
    BotsGet200ResponseToJSON,
    UserRoomsGet200ResponseFromJSON,
    UserRoomsGet200ResponseToJSON,
} from '../models/index';

export interface BotDetailGetRequest {
    bot_id?: number;
    bot_did?: string;
}

export interface BotsGetRequest {
    page_no?: number;
    page_size?: number;
    keyword?: string;
    body?: object;
}

export interface UserRoomsGetRequest {
    authorization?: string;
}

/**
 * 
 */
export class ImBotApi extends runtime.BaseAPI {

    /**
     * 输入参数为bot_id或bot_did
     * get bot detail info
     */
    async botDetailGetRaw(requestParameters: BotDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BotDetailGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['bot_id'] != null) {
            queryParameters['bot_id'] = requestParameters['bot_id'];
        }

        if (requestParameters['bot_did'] != null) {
            queryParameters['bot_did'] = requestParameters['bot_did'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bot/detail`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BotDetailGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 输入参数为bot_id或bot_did
     * get bot detail info
     */
    async botDetailGet(requestParameters: BotDetailGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BotDetailGet200Response> {
        const response = await this.botDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * get all bots
     */
    async botsGetRaw(requestParameters: BotsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BotsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page_no'] != null) {
            queryParameters['page_no'] = requestParameters['page_no'];
        }

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/bots`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BotsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * get all bots
     */
    async botsGet(requestParameters: BotsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BotsGet200Response> {
        const response = await this.botsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * user_id  like. @tasktalk:matrix.org
     * get user rooms
     */
    async userRoomsGetRaw(requestParameters: UserRoomsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRoomsGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/user/rooms`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserRoomsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * user_id  like. @tasktalk:matrix.org
     * get user rooms
     */
    async userRoomsGet(requestParameters: UserRoomsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRoomsGet200Response> {
        const response = await this.userRoomsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
