/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WalletdataChainConfigGet200Response,
  WalletdataEnsGet200Response,
  WalletdataGasTokenGet200Response,
  WalletdataTokensGet200Response,
  WalletdataTransferBalanceGet200Response,
} from '../models/index';
import {
    WalletdataChainConfigGet200ResponseFromJSON,
    WalletdataChainConfigGet200ResponseToJSON,
    WalletdataEnsGet200ResponseFromJSON,
    WalletdataEnsGet200ResponseToJSON,
    WalletdataGasTokenGet200ResponseFromJSON,
    WalletdataGasTokenGet200ResponseToJSON,
    WalletdataTokensGet200ResponseFromJSON,
    WalletdataTokensGet200ResponseToJSON,
    WalletdataTransferBalanceGet200ResponseFromJSON,
    WalletdataTransferBalanceGet200ResponseToJSON,
} from '../models/index';

export interface WalletdataActivityGetRequest {
    addr: string;
    page_num?: number;
    page_size?: number;
    Authorization?: string;
}

export interface WalletdataChainConfigGetRequest {
    Authorization?: string;
}

export interface WalletdataEnsGetRequest {
    query: string;
    Authorization?: string;
}

export interface WalletdataGasTokenGetRequest {
    chain_id: number;
    currency_name: string;
    Authorization?: string;
}

export interface WalletdataTokensGetRequest {
    addr: string;
    ont_id: string;
    Authorization?: string;
}

export interface WalletdataTransferBalanceGetRequest {
    chain_id: number;
    token_addr: string;
    addr: string;
    Authorization?: string;
}

/**
 * 
 */
export class ImWalletApi extends runtime.BaseAPI {

    /**
     * 
     * activity
     */
    async walletdataActivityGetRaw(requestParameters: WalletdataActivityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['addr'] == null) {
            throw new runtime.RequiredError(
                'addr',
                'Required parameter "addr" was null or undefined when calling walletdataActivityGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page_num'] != null) {
            queryParameters['page_num'] = requestParameters['page_num'];
        }

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        if (requestParameters['addr'] != null) {
            queryParameters['addr'] = requestParameters['addr'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        const response = await this.request({
            path: `/walletdata/activity`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * 
     * activity
     */
    async walletdataActivityGet(requestParameters: WalletdataActivityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.walletdataActivityGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * wallet_config
     */
    async walletdataChainConfigGetRaw(requestParameters: WalletdataChainConfigGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataChainConfigGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        const response = await this.request({
            path: `/walletdata/chain_config`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataChainConfigGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * wallet_config
     */
    async walletdataChainConfigGet(requestParameters: WalletdataChainConfigGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataChainConfigGet200Response> {
        const response = await this.walletdataChainConfigGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * ens
     */
    async walletdataEnsGetRaw(requestParameters: WalletdataEnsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataEnsGet200Response>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling walletdataEnsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        const response = await this.request({
            path: `/walletdata/ens`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataEnsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * ens
     */
    async walletdataEnsGet(requestParameters: WalletdataEnsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataEnsGet200Response> {
        const response = await this.walletdataEnsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * gas_token
     */
    async walletdataGasTokenGetRaw(requestParameters: WalletdataGasTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataGasTokenGet200Response>> {
        if (requestParameters['chain_id'] == null) {
            throw new runtime.RequiredError(
                'chain_id',
                'Required parameter "chain_id" was null or undefined when calling walletdataGasTokenGet().'
            );
        }

        if (requestParameters['currency_name'] == null) {
            throw new runtime.RequiredError(
                'currency_name',
                'Required parameter "currency_name" was null or undefined when calling walletdataGasTokenGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['chain_id'] != null) {
            queryParameters['chain_id'] = requestParameters['chain_id'];
        }

        if (requestParameters['currency_name'] != null) {
            queryParameters['currency_name'] = requestParameters['currency_name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        const response = await this.request({
            path: `/walletdata/gas_token`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataGasTokenGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * gas_token
     */
    async walletdataGasTokenGet(requestParameters: WalletdataGasTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataGasTokenGet200Response> {
        const response = await this.walletdataGasTokenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * tokens
     */
    async walletdataTokensGetRaw(requestParameters: WalletdataTokensGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataTokensGet200Response>> {
        if (requestParameters['addr'] == null) {
            throw new runtime.RequiredError(
                'addr',
                'Required parameter "addr" was null or undefined when calling walletdataTokensGet().'
            );
        }

        if (requestParameters['ont_id'] == null) {
            throw new runtime.RequiredError(
                'ont_id',
                'Required parameter "ont_id" was null or undefined when calling walletdataTokensGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['addr'] != null) {
            queryParameters['addr'] = requestParameters['addr'];
        }

        if (requestParameters['ont_id'] != null) {
            queryParameters['ont_id'] = requestParameters['ont_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        const response = await this.request({
            path: `/walletdata/tokens`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataTokensGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * tokens
     */
    async walletdataTokensGet(requestParameters: WalletdataTokensGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataTokensGet200Response> {
        const response = await this.walletdataTokensGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * transfer_balance
     */
    async walletdataTransferBalanceGetRaw(requestParameters: WalletdataTransferBalanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataTransferBalanceGet200Response>> {
        if (requestParameters['chain_id'] == null) {
            throw new runtime.RequiredError(
                'chain_id',
                'Required parameter "chain_id" was null or undefined when calling walletdataTransferBalanceGet().'
            );
        }

        if (requestParameters['token_addr'] == null) {
            throw new runtime.RequiredError(
                'token_addr',
                'Required parameter "token_addr" was null or undefined when calling walletdataTransferBalanceGet().'
            );
        }

        if (requestParameters['addr'] == null) {
            throw new runtime.RequiredError(
                'addr',
                'Required parameter "addr" was null or undefined when calling walletdataTransferBalanceGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['chain_id'] != null) {
            queryParameters['chain_id'] = requestParameters['chain_id'];
        }

        if (requestParameters['token_addr'] != null) {
            queryParameters['token_addr'] = requestParameters['token_addr'];
        }

        if (requestParameters['addr'] != null) {
            queryParameters['addr'] = requestParameters['addr'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        const response = await this.request({
            path: `/walletdata/transfer_balance`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataTransferBalanceGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * transfer_balance
     */
    async walletdataTransferBalanceGet(requestParameters: WalletdataTransferBalanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataTransferBalanceGet200Response> {
        const response = await this.walletdataTransferBalanceGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
