/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChainConfigGet200Response,
  EnsGet200Response,
  GasTokenGet200Response,
  TokensGet200Response,
  TransferBalanceGet200Response,
} from '../models/index';
import {
    ChainConfigGet200ResponseFromJSON,
    ChainConfigGet200ResponseToJSON,
    EnsGet200ResponseFromJSON,
    EnsGet200ResponseToJSON,
    GasTokenGet200ResponseFromJSON,
    GasTokenGet200ResponseToJSON,
    TokensGet200ResponseFromJSON,
    TokensGet200ResponseToJSON,
    TransferBalanceGet200ResponseFromJSON,
    TransferBalanceGet200ResponseToJSON,
} from '../models/index';

export interface ActivityGetRequest {
    addr: string;
    page_num?: number;
    page_size?: number;
}

export interface EnsGetRequest {
    query: string;
}

export interface GasTokenGetRequest {
    chain_id: number;
    currency_name: string;
}

export interface TokensGetRequest {
    addr: string;
    ont_id: string;
}

export interface TransferBalanceGetRequest {
    chain_id: number;
    token_addr: string;
    addr: string;
}

/**
 * 
 */
export class ImWalletApi extends runtime.BaseAPI {

    /**
     * 
     * activity
     */
    async activityGetRaw(requestParameters: ActivityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['addr'] == null) {
            throw new runtime.RequiredError(
                'addr',
                'Required parameter "addr" was null or undefined when calling activityGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page_num'] != null) {
            queryParameters['page_num'] = requestParameters['page_num'];
        }

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        if (requestParameters['addr'] != null) {
            queryParameters['addr'] = requestParameters['addr'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/activity`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * 
     * activity
     */
    async activityGet(requestParameters: ActivityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.activityGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * wallet_config
     */
    async chainConfigGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChainConfigGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/chain_config`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChainConfigGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * wallet_config
     */
    async chainConfigGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChainConfigGet200Response> {
        const response = await this.chainConfigGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * 
     * ens
     */
    async ensGetRaw(requestParameters: EnsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnsGet200Response>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling ensGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ens`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * ens
     */
    async ensGet(requestParameters: EnsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnsGet200Response> {
        const response = await this.ensGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * gas_token
     */
    async gasTokenGetRaw(requestParameters: GasTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GasTokenGet200Response>> {
        if (requestParameters['chain_id'] == null) {
            throw new runtime.RequiredError(
                'chain_id',
                'Required parameter "chain_id" was null or undefined when calling gasTokenGet().'
            );
        }

        if (requestParameters['currency_name'] == null) {
            throw new runtime.RequiredError(
                'currency_name',
                'Required parameter "currency_name" was null or undefined when calling gasTokenGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['chain_id'] != null) {
            queryParameters['chain_id'] = requestParameters['chain_id'];
        }

        if (requestParameters['currency_name'] != null) {
            queryParameters['currency_name'] = requestParameters['currency_name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/gas_token`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GasTokenGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * gas_token
     */
    async gasTokenGet(requestParameters: GasTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GasTokenGet200Response> {
        const response = await this.gasTokenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * tokens
     */
    async tokensGetRaw(requestParameters: TokensGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokensGet200Response>> {
        if (requestParameters['addr'] == null) {
            throw new runtime.RequiredError(
                'addr',
                'Required parameter "addr" was null or undefined when calling tokensGet().'
            );
        }

        if (requestParameters['ont_id'] == null) {
            throw new runtime.RequiredError(
                'ont_id',
                'Required parameter "ont_id" was null or undefined when calling tokensGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['addr'] != null) {
            queryParameters['addr'] = requestParameters['addr'];
        }

        if (requestParameters['ont_id'] != null) {
            queryParameters['ont_id'] = requestParameters['ont_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tokens`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokensGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * tokens
     */
    async tokensGet(requestParameters: TokensGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokensGet200Response> {
        const response = await this.tokensGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * transfer_balance
     */
    async transferBalanceGetRaw(requestParameters: TransferBalanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransferBalanceGet200Response>> {
        if (requestParameters['chain_id'] == null) {
            throw new runtime.RequiredError(
                'chain_id',
                'Required parameter "chain_id" was null or undefined when calling transferBalanceGet().'
            );
        }

        if (requestParameters['token_addr'] == null) {
            throw new runtime.RequiredError(
                'token_addr',
                'Required parameter "token_addr" was null or undefined when calling transferBalanceGet().'
            );
        }

        if (requestParameters['addr'] == null) {
            throw new runtime.RequiredError(
                'addr',
                'Required parameter "addr" was null or undefined when calling transferBalanceGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['chain_id'] != null) {
            queryParameters['chain_id'] = requestParameters['chain_id'];
        }

        if (requestParameters['token_addr'] != null) {
            queryParameters['token_addr'] = requestParameters['token_addr'];
        }

        if (requestParameters['addr'] != null) {
            queryParameters['addr'] = requestParameters['addr'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/transfer_balance`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferBalanceGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * transfer_balance
     */
    async transferBalanceGet(requestParameters: TransferBalanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransferBalanceGet200Response> {
        const response = await this.transferBalanceGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
