/* tslint:disable */
/* eslint-disable */
/**
 * IM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WalletdataActivityGet200Response,
  WalletdataChainConfigGet200Response,
  WalletdataChangeOwnerPost200Response,
  WalletdataChangeOwnerPostRequest,
  WalletdataConfirmPaymentPost200Response,
  WalletdataConfirmPaymentPostRequest,
  WalletdataEnsGet200Response,
  WalletdataExchangeRateGet200Response,
  WalletdataFeeTokensGet200Response,
  WalletdataGasTokenGet200Response,
  WalletdataRelayChainPostRequest,
  WalletdataTokensGet200Response,
  WalletdataTransferBalanceGet200Response,
} from '../models/index';
import {
    WalletdataActivityGet200ResponseFromJSON,
    WalletdataActivityGet200ResponseToJSON,
    WalletdataChainConfigGet200ResponseFromJSON,
    WalletdataChainConfigGet200ResponseToJSON,
    WalletdataChangeOwnerPost200ResponseFromJSON,
    WalletdataChangeOwnerPost200ResponseToJSON,
    WalletdataChangeOwnerPostRequestFromJSON,
    WalletdataChangeOwnerPostRequestToJSON,
    WalletdataConfirmPaymentPost200ResponseFromJSON,
    WalletdataConfirmPaymentPost200ResponseToJSON,
    WalletdataConfirmPaymentPostRequestFromJSON,
    WalletdataConfirmPaymentPostRequestToJSON,
    WalletdataEnsGet200ResponseFromJSON,
    WalletdataEnsGet200ResponseToJSON,
    WalletdataExchangeRateGet200ResponseFromJSON,
    WalletdataExchangeRateGet200ResponseToJSON,
    WalletdataFeeTokensGet200ResponseFromJSON,
    WalletdataFeeTokensGet200ResponseToJSON,
    WalletdataGasTokenGet200ResponseFromJSON,
    WalletdataGasTokenGet200ResponseToJSON,
    WalletdataRelayChainPostRequestFromJSON,
    WalletdataRelayChainPostRequestToJSON,
    WalletdataTokensGet200ResponseFromJSON,
    WalletdataTokensGet200ResponseToJSON,
    WalletdataTransferBalanceGet200ResponseFromJSON,
    WalletdataTransferBalanceGet200ResponseToJSON,
} from '../models/index';

export interface WalletdataActivityGetRequest {
    addr: string;
    page_num?: number;
    page_size?: number;
    chain_id?: number;
    Authorization?: string;
}

export interface WalletdataChainConfigGetRequest {
    Authorization?: string;
}

export interface WalletdataChangeOwnerPostOperationRequest {
    WalletdataChangeOwnerPostRequest?: WalletdataChangeOwnerPostRequest;
}

export interface WalletdataConfirmPaymentPostOperationRequest {
    Authorization?: string;
    WalletdataConfirmPaymentPostRequest?: WalletdataConfirmPaymentPostRequest;
}

export interface WalletdataEnsGetRequest {
    query: string;
    Authorization?: string;
}

export interface WalletdataExchangeRateGetRequest {
    chain_id: number;
    from_token_hash?: string;
    to_token_hash?: string;
    Authorization?: string;
}

export interface WalletdataFeeTokensGetRequest {
    Authorization?: string;
}

export interface WalletdataGasTokenGetRequest {
    chain_id: number;
    currency_name?: string;
    Authorization?: string;
}

export interface WalletdataRelayChainPostOperationRequest {
    WalletdataRelayChainPostRequest?: WalletdataRelayChainPostRequest;
}

export interface WalletdataTokensGetRequest {
    addr: string;
    ont_id: string;
    Authorization?: string;
}

export interface WalletdataTransferBalanceGetRequest {
    chain_id: number;
    addr: string;
    token_addr?: string;
    Authorization?: string;
}

/**
 * 
 */
export class ImWalletApi extends runtime.BaseAPI {

    /**
     * 
     * activity
     */
    async walletdataActivityGetRaw(requestParameters: WalletdataActivityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataActivityGet200Response>> {
        if (requestParameters['addr'] == null) {
            throw new runtime.RequiredError(
                'addr',
                'Required parameter "addr" was null or undefined when calling walletdataActivityGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page_num'] != null) {
            queryParameters['page_num'] = requestParameters['page_num'];
        }

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        if (requestParameters['addr'] != null) {
            queryParameters['addr'] = requestParameters['addr'];
        }

        if (requestParameters['chain_id'] != null) {
            queryParameters['chain_id'] = requestParameters['chain_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/walletdata/activity`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataActivityGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * activity
     */
    async walletdataActivityGet(requestParameters: WalletdataActivityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataActivityGet200Response> {
        const response = await this.walletdataActivityGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * wallet_config
     */
    async walletdataChainConfigGetRaw(requestParameters: WalletdataChainConfigGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataChainConfigGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/walletdata/chain_config`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataChainConfigGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * wallet_config
     */
    async walletdataChainConfigGet(requestParameters: WalletdataChainConfigGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataChainConfigGet200Response> {
        const response = await this.walletdataChainConfigGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * change_owner
     */
    async walletdataChangeOwnerPostRaw(requestParameters: WalletdataChangeOwnerPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataChangeOwnerPost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/walletdata/change_owner`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WalletdataChangeOwnerPostRequestToJSON(requestParameters['WalletdataChangeOwnerPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataChangeOwnerPost200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * change_owner
     */
    async walletdataChangeOwnerPost(requestParameters: WalletdataChangeOwnerPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataChangeOwnerPost200Response> {
        const response = await this.walletdataChangeOwnerPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * confirm_payment
     */
    async walletdataConfirmPaymentPostRaw(requestParameters: WalletdataConfirmPaymentPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataConfirmPaymentPost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/walletdata/confirm_payment`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WalletdataConfirmPaymentPostRequestToJSON(requestParameters['WalletdataConfirmPaymentPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataConfirmPaymentPost200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * confirm_payment
     */
    async walletdataConfirmPaymentPost(requestParameters: WalletdataConfirmPaymentPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataConfirmPaymentPost200Response> {
        const response = await this.walletdataConfirmPaymentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * ens
     */
    async walletdataEnsGetRaw(requestParameters: WalletdataEnsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataEnsGet200Response>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling walletdataEnsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/walletdata/ens`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataEnsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * ens
     */
    async walletdataEnsGet(requestParameters: WalletdataEnsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataEnsGet200Response> {
        const response = await this.walletdataEnsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * exchange_rate
     */
    async walletdataExchangeRateGetRaw(requestParameters: WalletdataExchangeRateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataExchangeRateGet200Response>> {
        if (requestParameters['chain_id'] == null) {
            throw new runtime.RequiredError(
                'chain_id',
                'Required parameter "chain_id" was null or undefined when calling walletdataExchangeRateGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['chain_id'] != null) {
            queryParameters['chain_id'] = requestParameters['chain_id'];
        }

        if (requestParameters['from_token_hash'] != null) {
            queryParameters['from_token_hash'] = requestParameters['from_token_hash'];
        }

        if (requestParameters['to_token_hash'] != null) {
            queryParameters['to_token_hash'] = requestParameters['to_token_hash'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/walletdata/exchange_rate`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataExchangeRateGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * exchange_rate
     */
    async walletdataExchangeRateGet(requestParameters: WalletdataExchangeRateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataExchangeRateGet200Response> {
        const response = await this.walletdataExchangeRateGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * fee_tokens
     */
    async walletdataFeeTokensGetRaw(requestParameters: WalletdataFeeTokensGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataFeeTokensGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/walletdata/fee_tokens`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataFeeTokensGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * fee_tokens
     */
    async walletdataFeeTokensGet(requestParameters: WalletdataFeeTokensGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataFeeTokensGet200Response> {
        const response = await this.walletdataFeeTokensGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 支持的gas列表
     */
    async walletdataGasTokenGetRaw(requestParameters: WalletdataGasTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataGasTokenGet200Response>> {
        if (requestParameters['chain_id'] == null) {
            throw new runtime.RequiredError(
                'chain_id',
                'Required parameter "chain_id" was null or undefined when calling walletdataGasTokenGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['chain_id'] != null) {
            queryParameters['chain_id'] = requestParameters['chain_id'];
        }

        if (requestParameters['currency_name'] != null) {
            queryParameters['currency_name'] = requestParameters['currency_name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/walletdata/gas_token`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataGasTokenGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * 支持的gas列表
     */
    async walletdataGasTokenGet(requestParameters: WalletdataGasTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataGasTokenGet200Response> {
        const response = await this.walletdataGasTokenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * relay_chain
     */
    async walletdataRelayChainPostRaw(requestParameters: WalletdataRelayChainPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataChangeOwnerPost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/walletdata/relay_chain`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WalletdataRelayChainPostRequestToJSON(requestParameters['WalletdataRelayChainPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataChangeOwnerPost200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * relay_chain
     */
    async walletdataRelayChainPost(requestParameters: WalletdataRelayChainPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataChangeOwnerPost200Response> {
        const response = await this.walletdataRelayChainPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * tokens
     */
    async walletdataTokensGetRaw(requestParameters: WalletdataTokensGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataTokensGet200Response>> {
        if (requestParameters['addr'] == null) {
            throw new runtime.RequiredError(
                'addr',
                'Required parameter "addr" was null or undefined when calling walletdataTokensGet().'
            );
        }

        if (requestParameters['ont_id'] == null) {
            throw new runtime.RequiredError(
                'ont_id',
                'Required parameter "ont_id" was null or undefined when calling walletdataTokensGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['addr'] != null) {
            queryParameters['addr'] = requestParameters['addr'];
        }

        if (requestParameters['ont_id'] != null) {
            queryParameters['ont_id'] = requestParameters['ont_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/walletdata/tokens`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataTokensGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * tokens
     */
    async walletdataTokensGet(requestParameters: WalletdataTokensGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataTokensGet200Response> {
        const response = await this.walletdataTokensGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 查账户中的某个token
     */
    async walletdataTransferBalanceGetRaw(requestParameters: WalletdataTransferBalanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletdataTransferBalanceGet200Response>> {
        if (requestParameters['chain_id'] == null) {
            throw new runtime.RequiredError(
                'chain_id',
                'Required parameter "chain_id" was null or undefined when calling walletdataTransferBalanceGet().'
            );
        }

        if (requestParameters['addr'] == null) {
            throw new runtime.RequiredError(
                'addr',
                'Required parameter "addr" was null or undefined when calling walletdataTransferBalanceGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['chain_id'] != null) {
            queryParameters['chain_id'] = requestParameters['chain_id'];
        }

        if (requestParameters['token_addr'] != null) {
            queryParameters['token_addr'] = requestParameters['token_addr'];
        }

        if (requestParameters['addr'] != null) {
            queryParameters['addr'] = requestParameters['addr'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['Authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['Authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/walletdata/transfer_balance`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletdataTransferBalanceGet200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * 查账户中的某个token
     */
    async walletdataTransferBalanceGet(requestParameters: WalletdataTransferBalanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletdataTransferBalanceGet200Response> {
        const response = await this.walletdataTransferBalanceGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
